config :bundle_test,
  :required => [:sproutcore, 'bundle_test/static'],
  :dynamic_required => ['bundle_test/dynamic'],
  :use_modules => true

config :static, 
  :required => [],
  :use_modules => true
  
config :dynamic, 
  :required => [],
  :use_modules => true
