// ==========================================================================
// SampleControls
// copyright 2008 Sprout Systems, Inc.
// ==========================================================================
/*global SampleControls tile */
/*
require('views/control_sample');


SampleControls.mainPage = SC.Page.create({
  
  pageName: 'SampleControls.mainPage',
  
  mainPane: SC.MainPane.design({

    childViews: [SC.TabView.design({
      
      nowShowing: 'welcome',

      items: [
        { title: "Welcome", value: "welcome" },
        { title: "Controls", value: "SampleControls.controlsPage.mainView" },
        { title: "Form", value: "SampleControls.formsPage.mainView" },
        { title: "Icons", value: "SampleControls.iconsPage.mainView" }
      ],
      
      itemTitleKey: 'title',
      itemValueKey: 'value',
            
      layout: { left:12, right:12, top:12, bottom:12 },
      
      userDefaultKey: "mainPane"
      
    })]
    
  }),

  welcome: SC.LabelView.design({
    escapeHTML: NO,
    styleClass: 'welcome-tab',
    value: "<h1>Sample Controls</h1><p>SproutCore comes bundled with a wide array of controls that you can use in your own applications. Most of these controls can be created very easily using the built-in view helper functions. Consult the source code of this application for samples code to use in your own application.</p>"
  })
  
});

*/

// SproutCore ViewBuilder Design Format v1.0
// WARNING: This file is automatically generated.  DO NOT EDIT.  Changes you
// make to this file will be lost.

SampleControls.mainPage = SC.Page.design({mainPane: SC.MainPane.design({childViews: [SC.TabView.design({nowShowing: "welcome",items: [{title: "Welcome",value: "welcome"},{title: "Controls",value: "SampleControls.controlsPage.mainView"},{title: "Form",value: "SampleControls.formsPage.mainView"},{title: "Icons",value: "SampleControls.iconsPage.mainView"}],itemTitleKey: "title",itemValueKey: "value",userDefaultKey: "mainPane",rootElementPath: [0]})]}),welcome: SC.LabelView.design({styleClass: ["sc-view","sc-label-view","welcome-tab"],value: "<h1>Sample Controls</h1><p>SproutCore comes bundled with a wide array of controls that you can use in your own applications. Most of these controls can be created very easily using the built-in view helper functions. Consult the source code of this application for samples code to use in your own application.</p>",escapeHTML: NO,rootElementPath: [0]}),pageName: "SampleControls.mainPage"});


// SproutCore ViewBuilder Localization Format v1.0
// WARNING: This file is automatically generated.  DO NOT EDIT.  Changes you
// make to this file will be lost.

SampleControls.mainPage.loc(SC.Page.localization({mainPane: SC.MainPane.localization({childViews: [SC.TabView.localization({layout: {left: 12,right: 12,top: 12,bottom: 12}})]}, '<div class="sc-pane sc-main-pane sc-view" style="left: 0px; right: 0px; top: 0px; bottom: 0px; "><div class="sc-view sc-tab-view" style="left: 12px; right: 12px; top: 12px; bottom: 12px; "><div class="sc-view sc-container-view" style="left: 0px; right: 0px; top: 11px; bottom: 0px; "></div><div class="sc-view sc-segmented-view sc-layout-horizontal sc-regular-size" style="left: 0px; right: 0px; top: 0px; height: 23px; "><a href="javascript:;" class="sc-segment sc-first-segment sel" role="tab" style="width: 0px; margin-left: 0px; "><span class="sc-button-inner"><label class="sc-button-label">Welcome</label></span></a><a href="javascript:;" class="sc-segment sc-middle-segment" role="tab" style="width: 0px; margin-left: 0px; "><span class="sc-button-inner"><label class="sc-button-label">Controls</label></span></a><a href="javascript:;" class="sc-segment sc-middle-segment" role="tab" style="width: 0px; margin-left: 0px; "><span class="sc-button-inner"><label class="sc-button-label">Form</label></span></a><a href="javascript:;" class="sc-segment  sc-last-segment" role="tab" style="width: 0px; margin-left: 0px; "><span class="sc-button-inner"><label class="sc-button-label">Icons</label></span></a></div></div></div>'),welcome:   SC.LabelView.localization({}, '<div class="sc-view sc-label-view welcome-tab sc-regular-size" style="left: 0px; right: 0px; top: 0px; bottom: 0px; text-align: left; font-weight: normal; "><h1>Sample Controls</h1><p>SproutCore comes bundled with a wide array of controls that you can use in your own applications. Most of these controls can be created very easily using the built-in view helper functions. Consult the source code of this application for samples code to use in your own application.</p></div>')}));

