// ==========================================================================
// Project:   TableView.Movie Fixtures
// Copyright: ©2010 My Company, Inc.
// ==========================================================================
/*globals TableView */

sc_require('models/movie');

/**
  Since this is a sample app, the "fixtures" directory is renamed to 
  "fixtures-prod", meaming this fixture data will be available at all times,
  even in production mode.
*/
TableView.Movie.FIXTURES = [
  {'seen': '0', 'rating': '9.1', 'votes': '215405', 'title': 'The Shawshank Redemption'},
   {'seen': '0', 'rating': '8.8', 'votes': '206072', 'title': 'The Lord of the Rings: The Fellowship of the Ring'},

   {'seen': '0', 'rating': '8.6', 'votes': '188811', 'title': 'The Matrix'},
   {'seen': '0', 'rating': '8.8', 'votes': '185100', 'title': 'Pulp Fiction'},
   {'seen': '0', 'rating': '9.1', 'votes': '178881', 'title': 'The Godfather'},
   {'seen': '0', 'rating': '8.8', 'votes': '176346', 'title': 'Star Wars'},
   {'seen': '0', 'rating': '8.9', 'votes': '162436', 'title': 'The Lord of the Rings: The Return of the King'},
   {'seen': '0', 'rating': '8.7', 'votes': '162001', 'title': 'The Lord of the Rings: The Two Towers'},
   {'seen': '0', 'rating': '8.6', 'votes': '160135', 'title': 'Fight Club'},
   {'seen': '0', 'rating': '8.5', 'votes': '143775', 'title': 'American Beauty'},
   {'seen': '0', 'rating': '8.8', 'votes': '139813', 'title': 'Star Wars: Episode V - The Empire Strikes Back'},
   {'seen': '0', 'rating': '8.7', 'votes': '136641', 'title': 'The Usual Suspects'},
   {'seen': '0', 'rating': '8.4', 'votes': '131936', 'title': 'Saving Private Ryan'},
   {'seen': '0', 'rating': '8.8', 'votes': '130036', 'title': "Schindler's List"},
   {'seen': '0', 'rating': '8.2', 'votes': '125831', 'title': 'The Sixth Sense'},
   {'seen': '0', 'rating': '8.3', 'votes': '125224', 'title': 'Forrest Gump'},
   {'seen': '0', 'rating': '8.1', 'votes': '125137', 'title': 'Gladiator'},
   {'seen': '0', 'rating': '8.6', 'votes': '124731', 'title': 'Memento'},
   {'seen': '0', 'rating': '8.5', 'votes': '121730', 'title': 'Se7en'},
   {'seen': '0', 'rating': '8.7', 'votes': '120597', 'title': 'Raiders of the Lost Ark'},
   {'seen': '0', 'rating': '8.3', 'votes': '120485', 'title': 'Braveheart'},
   {'seen': '0', 'rating': '8.6', 'votes': '119366', 'title': 'The Silence of the Lambs'},
   {'seen': '0', 'rating': '7', 'votes': '117267', 'title': 'Titanic'},
   {'seen': '0', 'rating': '6.3', 'votes': '113240', 'title': 'Star Wars: Episode I - The Phantom Menace'},
   {'seen': '0', 'rating': '8.2', 'votes': '111044', 'title': 'Star Wars: Episode VI - Return of the Jedi'},
   {'seen': '0', 'rating': '8.2', 'votes': '102337', 'title': 'Terminator 2: Judgment Day'},
   {'seen': '0', 'rating': '9', 'votes': '101625', 'title': 'The Godfather: Part II'},
   {'seen': '0', 'rating': '8', 'votes': '100521', 'title': 'Pirates of the Caribbean: The Curse of the Black Pearl'},
   {'seen': '0', 'rating': '8.2', 'votes': '97734', 'title': 'Kill Bill: Vol. 1'},
   {'seen': '0', 'rating': '8', 'votes': '96012', 'title': 'Star Wars: Episode III - Revenge of the Sith'},
   {'seen': '0', 'rating': '8.7', 'votes': '94979', 'title': 'Goodfellas'},
   {'seen': '0', 'rating': '8.4', 'votes': '94930', 'title': 'Reservoir Dogs'},
   {'seen': '0', 'rating': '8.3', 'votes': '94455', 'title': 'Blade Runner'},
   {'seen': '0', 'rating': '8.8', 'votes': '94055', 'title': "One Flew Over the Cuckoo's Nest"},
   {'seen': '0', 'rating': '8.4', 'votes': '93766', 'title': 'Batman Begins'},
   {'seen': '0', 'rating': '8.1', 'votes': '92155', 'title': 'Back to the Future'},
   {'seen': '0', 'rating': '8.4', 'votes': '91239', 'title': 'Sin City'},
   {'seen': '0', 'rating': '6.9', 'votes': '90430', 'title': 'Star Wars: Episode II - Attack of the Clones'},
   {'seen': '0', 'rating': '8.4', 'votes': '88992', 'title': 'L.A. Confidential'},
   {'seen': '0', 'rating': '8', 'votes': '88541', 'title': 'Shrek'},
   {'seen': '0', 'rating': '8.4', 'votes': '88499', 'title': 'A Clockwork Orange'},
   {'seen': '0', 'rating': '8.8', 'votes': '87517', 'title': 'Casablanca'},
   {'seen': '0', 'rating': '8.5', 'votes': '87391', 'title': 'American History X'},
   {'seen': '0', 'rating': '8.5', 'votes': '86478', 'title': 'Apocalypse Now'},
   {'seen': '0', 'rating': '8.3', 'votes': '85723', 'title': 'Donnie Darko'},
   {'seen': '0', 'rating': '7.4', 'votes': '85323', 'title': 'Spider-Man'},
   {'seen': '0', 'rating': '8.6', 'votes': '85077', 'title': "Le Fabuleux destin d'Am"},
   {'seen': '0', 'rating': '8.5', 'votes': '85042', 'title': 'Eternal Sunshine of the Spotless Mind'},
   {'seen': '0', 'rating': '8.1', 'votes': '84206', 'title': 'The Green Mile'},
   {'seen': '0', 'rating': '8.4', 'votes': '83929', 'title': 'Alien'},
   {'seen': '0', 'rating': '8.2', 'votes': '83897', 'title': 'Fargo'},
   {'seen': '0', 'rating': '8.7', 'votes': '83862', 'title': 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb'},
   {'seen': '0', 'rating': '8.3', 'votes': '83435', 'title': '2001: A Space Odyssey'},
   {'seen': '0', 'rating': '8.3', 'votes': '83084', 'title': 'Aliens'},
   {'seen': '0', 'rating': '8', 'votes': '81813', 'title': 'Twelve Monkeys'},
   {'seen': '0', 'rating': '8.4', 'votes': '81685', 'title': 'Monty Python and the Holy Grail'},
   {'seen': '0', 'rating': '8.1', 'votes': '80477', 'title': 'Indiana Jones and the Last Crusade'},
   {'seen': '0', 'rating': '7.8', 'votes': '79527', 'title': 'The Truman Show'},
   {'seen': '0', 'rating': '7.9', 'votes': '78718', 'title': 'The Terminator'},
   {'seen': '0', 'rating': '8.6', 'votes': '78346', 'title': 'Citizen Kane'},
   {'seen': '0', 'rating': '6.1', 'votes': '77696', 'title': 'Independence Day'},
   {'seen': '0', 'rating': '8', 'votes': '77564', 'title': 'Die Hard'},
   {'seen': '0', 'rating': '8.5', 'votes': '77344', 'title': 'L'},
   {'seen': '0', 'rating': '7.5', 'votes': '76946', 'title': 'Jurassic Park'},
   {'seen': '0', 'rating': '7', 'votes': '76262', 'title': 'The Matrix Reloaded'},
   {'seen': '0', 'rating': '7.9', 'votes': '75870', 'title': 'Good Will Hunting'},
   {'seen': '0', 'rating': '8.4', 'votes': '73221', 'title': 'Requiem for a Dream'},
   {'seen': '0', 'rating': '8.2', 'votes': '71708', 'title': 'Kill Bill: Vol. 2'},
   {'seen': '0', 'rating': '8', 'votes': '71634', 'title': 'The Big Lebowski'},
   {'seen': '0', 'rating': '8.4', 'votes': '71316', 'title': 'The Shining'},
   {'seen': '0', 'rating': '7.8', 'votes': '71224', 'title': 'Being John Malkovich'},
   {'seen': '0', 'rating': '8.6', 'votes': '70599', 'title': 'Psycho'},
   {'seen': '0', 'rating': '7.2', 'votes': '70455', 'title': 'The Fifth Element'},
   {'seen': '0', 'rating': '8', 'votes': '70050', 'title': 'Trainspotting'},
   {'seen': '0', 'rating': '8.2', 'votes': '69523', 'title': 'The Princess Bride'},
   {'seen': '0', 'rating': '7.7', 'votes': '68746', 'title': 'Minority Report'},
   {'seen': '0', 'rating': '8.3', 'votes': '67182', 'title': 'Crash'},
   {'seen': '0', 'rating': '7.9', 'votes': '66600', 'title': 'Lost in Translation'},
   {'seen': '0', 'rating': '8', 'votes': '66039', 'title': 'Snatch.'},
   {'seen': '0', 'rating': '6.8', 'votes': '66029', 'title': 'Men in Black'},
   {'seen': '0', 'rating': '8.3', 'votes': '65909', 'title': 'V for Vendetta'},
   {'seen': '0', 'rating': '8.5', 'votes': '65692', 'title': 'Taxi Driver'},
   {'seen': '0', 'rating': '8.2', 'votes': '65359', 'title': 'Full Metal Jacket'},
   {'seen': '0', 'rating': '7.8', 'votes': '65085', 'title': 'King Kong'},
   {'seen': '0', 'rating': '8.2', 'votes': '65040', 'title': 'Wo hu cang long'},
   {'seen': '0', 'rating': '7.2', 'votes': '64378', 'title': "Harry Potter and the Sorcerer's Stone"},
   {'seen': '0', 'rating': '8.3', 'votes': '64263', 'title': 'Jaws'},
   {'seen': '0', 'rating': '8.2', 'votes': '63885', 'title': 'Finding Nemo'},
   {'seen': '0', 'rating': '7.8', 'votes': '63470', 'title': 'Spider-Man 2'},
   {'seen': '0', 'rating': '8', 'votes': '62772', 'title': 'Heat'},
   {'seen': '0', 'rating': '7.7', 'votes': '62299', 'title': 'Moulin Rouge!'},
   {'seen': '0', 'rating': '7.5', 'votes': '62296', 'title': "Ocean's Eleven"},
   {'seen': '0', 'rating': '6.7', 'votes': '62294', 'title': 'War of the Worlds'},
   {'seen': '0', 'rating': '8', 'votes': '62085', 'title': 'Magnolia'},
   {'seen': '0', 'rating': '7.3', 'votes': '61712', 'title': 'X-Men'},
   {'seen': '0', 'rating': '8', 'votes': '60784', 'title': 'Groundhog Day'},
   {'seen': '0', 'rating': '8', 'votes': '60516', 'title': 'Toy Story'},
   {'seen': '0', 'rating': '5.7', 'votes': '59402', 'title': 'Armageddon'},
   {'seen': '0', 'rating': '7.6', 'votes': '59263', 'title': 'Catch Me If You Can'},
   {'seen': '0', 'rating': '7.8', 'votes': '58896', 'title': 'A Beautiful Mind'},
   {'seen': '0', 'rating': '7.1', 'votes': '58581', 'title': 'Rock, The '},
   {'seen': '0', 'rating': '7.7', 'votes': '58325', 'title': 'Fugitive, The '},
   {'seen': '0', 'rating': '7.3', 'votes': '57968', 'title': 'Harry Potter and the Chamber of Secrets '},
   {'seen': '0', 'rating': '7.1', 'votes': '57108', 'title': "There's Something About Mary "},
   {'seen': '0', 'rating': '7.3', 'votes': '57091', 'title': 'Dogma '},
   {'seen': '0', 'rating': '8.3', 'votes': '57041', 'title': 'Incredibles, The '},
   {'seen': '0', 'rating': '6.3', 'votes': '56864', 'title': 'Matrix Revolutions, The '},
   {'seen': '0', 'rating': '7.8', 'votes': '56494', 'title': 'E.T. the Extra-Terrestrial '},
   {'seen': '0', 'rating': '7.7', 'votes': '56450', 'title': 'As Good as It Gets '},
   {'seen': '0', 'rating': '7.9', 'votes': '56244', 'title': 'Rain Man '},
   {'seen': '0', 'rating': '7.9', 'votes': '56206', 'title': 'Brokeback Mountain '},
   {'seen': '0', 'rating': '7.9', 'votes': '55972', 'title': 'X2 '},
   {'seen': '0', 'rating': '8.7', 'votes': '55543', 'title': 'Rear Window '},
   {'seen': '0', 'rating': '6.9', 'votes': '55327', 'title': 'Signs '},
   {'seen': '0', 'rating': '8.1', 'votes': '54173', 'title': 'Toy Story 2 '},
   {'seen': '0', 'rating': '6.8', 'votes': '54144', 'title': 'American Pie '},
   {'seen': '0', 'rating': '7.9', 'votes': '54069', 'title': 'Monsters, Inc. '},
   {'seen': '0', 'rating': '7.7', 'votes': '53768', 'title': 'Dead Poets Society '},
   {'seen': '0', 'rating': '7', 'votes': '53377', 'title': 'Scream '},
   {'seen': '0', 'rating': '7.4', 'votes': '53244', 'title': 'Sleepy Hollow '},
   {'seen': '0', 'rating': '7.9', 'votes': '53200', 'title': 'Almost Famous '},
   {'seen': '0', 'rating': '8', 'votes': '53200', 'title': 'Big Fish '},
   {'seen': '0', 'rating': '8.6', 'votes': '52946', 'title': "It's a Wonderful Life "},
   {'seen': '0', 'rating': '7', 'votes': '52248', 'title': 'Troy '},
   {'seen': '0', 'rating': '7.9', 'votes': '51949', 'title': 'Clerks. '},
   {'seen': '0', 'rating': '7.8', 'votes': '51262', 'title': 'Traffic '},
   {'seen': '0', 'rating': '8.8', 'votes': '51192', 'title': 'Cidade de Deus '},
   {'seen': '0', 'rating': '7.9', 'votes': '51026', 'title': 'Mulholland Dr. '},
   {'seen': '0', 'rating': '7.5', 'votes': '50838', 'title': 'Apollo 13 '},
   {'seen': '0', 'rating': '8.3', 'votes': '50808', 'title': 'Million Dollar Baby '},
   {'seen': '0', 'rating': '7.5', 'votes': '50744', 'title': 'Batman '},
   {'seen': '0', 'rating': '7.4', 'votes': '50626', 'title': 'Shakespeare in Love '},
   {'seen': '0', 'rating': '8.4', 'votes': '50610', 'title': 'Vita '},
   {'seen': '0', 'rating': '8.2', 'votes': '50545', 'title': 'Wizard of Oz, The '},
   {'seen': '0', 'rating': '7.2', 'votes': '50179', 'title': 'Gangs of New York '},
   {'seen': '0', 'rating': '6', 'votes': '49788', 'title': 'Blair Witch Project, The '},
   {'seen': '0', 'rating': '7', 'votes': '49578', 'title': 'Eyes Wide Shut '},
   {'seen': '0', 'rating': '8', 'votes': '49438', 'title': 'Scarface '},
   {'seen': '0', 'rating': '8', 'votes': '49330', 'title': 'Lock, Stock and Two Smoking Barrels '},
   {'seen': '0', 'rating': '8.1', 'votes': '49131', 'title': 'Serenity '},
   {'seen': '0', 'rating': '7.4', 'votes': '49082', 'title': 'Chicago '},
   {'seen': '0', 'rating': '8.5', 'votes': '48963', 'title': 'Pianist, The '},
   {'seen': '0', 'rating': '8.9', 'votes': '48897', 'title': 'Buono, il brutto, il cattivo, Il '},
   {'seen': '0', 'rating': '7.8', 'votes': '48877', 'title': 'O Brother, Where Art Thou? '},
   {'seen': '0', 'rating': '8.3', 'votes': '48839', 'title': 'Bowling for Columbine '},
   {'seen': '0', 'rating': '8.3', 'votes': '48445', 'title': 'Amadeus '},
   {'seen': '0', 'rating': '8.1', 'votes': '48391', 'title': 'Platoon '},
   {'seen': '0', 'rating': '7.3', 'votes': '48372', 'title': "Pirates of the Caribbean: Dead Man's Chest "},
   {'seen': '0', 'rating': '7.1', 'votes': '48280', 'title': 'Face/Off '},
   {'seen': '0', 'rating': '8', 'votes': '48124', 'title': 'Garden State '},
   {'seen': '0', 'rating': '7.8', 'votes': '47942', 'title': 'Others, The '},
   {'seen': '0', 'rating': '6.8', 'votes': '47902', 'title': 'Artificial Intelligence: AI '},
   {'seen': '0', 'rating': '7.1', 'votes': '47718', 'title': 'Unbreakable '},
   {'seen': '0', 'rating': '5.7', 'votes': '47620', 'title': 'Mission: Impossible II '},
   {'seen': '0', 'rating': '6.5', 'votes': '47468', 'title': 'Austin Powers: The Spy Who Shagged Me '},
   {'seen': '0', 'rating': '7.3', 'votes': '47351', 'title': 'Passion of the Christ, The '},
   {'seen': '0', 'rating': '6.6', 'votes': '47333', 'title': 'Mummy, The '},
   {'seen': '0', 'rating': '7.8', 'votes': '47216', 'title': 'Last Samurai, The '},
   {'seen': '0', 'rating': '8.8', 'votes': '47059', 'title': 'Shichinin no samurai '},
   {'seen': '0', 'rating': '8.6', 'votes': '47054', 'title': 'North by Northwest '},
   {'seen': '0', 'rating': '7.2', 'votes': '47002', 'title': 'Indiana Jones and the Temple of Doom '},
   {'seen': '0', 'rating': '8', 'votes': '46766', 'title': 'Exorcist, The '},
   {'seen': '0', 'rating': '7.3', 'votes': '46702', 'title': 'Cast Away '},
   {'seen': '0', 'rating': '7.8', 'votes': '46487', 'title': 'Harry Potter and the Goblet of Fire '},
   {'seen': '0', 'rating': '7.9', 'votes': '46182', 'title': 'Lion King, The '},
   {'seen': '0', 'rating': '7.7', 'votes': '46068', 'title': 'Fahrenheit 9/11 '},
   {'seen': '0', 'rating': '8', 'votes': '45784', 'title': 'Mystic River '},
   {'seen': '0', 'rating': '5.3', 'votes': '45530', 'title': 'Pearl Harbor '},
   {'seen': '0', 'rating': '7.6', 'votes': '45359', 'title': 'Black Hawk Down '},
   {'seen': '0', 'rating': '8.5', 'votes': '45061', 'title': 'Vertigo '},
   {'seen': '0', 'rating': '6.8', 'votes': '45017', 'title': 'Terminator 3: Rise of the Machines '},
   {'seen': '0', 'rating': '8.1', 'votes': '44992', 'title': 'Life of Brian '},
   {'seen': '0', 'rating': '7.3', 'votes': '44512', 'title': 'Contact '},
   {'seen': '0', 'rating': '6.6', 'votes': '44474', 'title': 'Mission: Impossible '},
   {'seen': '0', 'rating': '7.6', 'votes': '44261', 'title': 'South Park: Bigger Longer & Uncut '},
   {'seen': '0', 'rating': '6.8', 'votes': '43897', 'title': 'Vanilla Sky '},
   {'seen': '0', 'rating': '7.2', 'votes': '43845', 'title': 'Jerry Maguire '},
   {'seen': '0', 'rating': '8.1', 'votes': '43476', 'title': 'Lola rennt '},
   {'seen': '0', 'rating': '7.4', 'votes': '43391', 'title': 'Bourne Identity, The '},
   {'seen': '0', 'rating': '7.6', 'votes': '43102', 'title': 'Saw '},
   {'seen': '0', 'rating': '7.7', 'votes': '43077', 'title': 'Collateral '},
   {'seen': '0', 'rating': '7.7', 'votes': '43032', 'title': 'Shrek 2 '},
   {'seen': '0', 'rating': '7.5', 'votes': '42906', 'title': 'Royal Tenenbaums, The '},
   {'seen': '0', 'rating': '7.8', 'votes': '42837', 'title': 'Harry Potter and the Prisoner of Azkaban '},
   {'seen': '0', 'rating': '7.3', 'votes': '42664', 'title': 'Ring, The '},
   {'seen': '0', 'rating': '7.9', 'votes': '42663', 'title': 'Untouchables, The '},
   {'seen': '0', 'rating': '7.1', 'votes': '42427', 'title': 'Austin Powers: International Man of Mystery '},
   {'seen': '0', 'rating': '6.5', 'votes': '42301', 'title': 'Top Gun '},
   {'seen': '0', 'rating': '7.5', 'votes': '42095', 'title': 'Charlie and the Chocolate Factory '},
   {'seen': '0', 'rating': '8.2', 'votes': '41801', 'title': 'Unforgiven '},
   {'seen': '0', 'rating': '7.3', 'votes': '41783', 'title': 'Chronicles of Narnia: The Lion, the Witch and the Wardrobe, The '},
   {'seen': '0', 'rating': '6.6', 'votes': '41740', 'title': 'Village, The '},
   {'seen': '0', 'rating': '7', 'votes': '41689', 'title': 'Meet the Parents '},
   {'seen': '0', 'rating': '8.1', 'votes': '41669', 'title': 'Stand by Me '},
   {'seen': '0', 'rating': '7.8', 'votes': '41636', 'title': "Ferris Bueller's Day Off "},
   {'seen': '0', 'rating': '8.7', 'votes': '41605', 'title': '12 Angry Men '},
   {'seen': '0', 'rating': '7.1', 'votes': '41564', 'title': 'Speed '},
   {'seen': '0', 'rating': '7', 'votes': '41526', 'title': 'X-Men: The Last Stand '},
   {'seen': '0', 'rating': '7.7', 'votes': '41498', 'title': 'Road to Perdition '},
   {'seen': '0', 'rating': '7.8', 'votes': '41421', 'title': 'Edward Scissorhands '},
   {'seen': '0', 'rating': '6.7', 'votes': '41395', 'title': 'Starship Troopers '},
   {'seen': '0', 'rating': '8.5', 'votes': '41145', 'title': 'To Kill a Mockingbird '},
   {'seen': '0', 'rating': '6.5', 'votes': '41113', 'title': 'Da Vinci Code, The '},
   {'seen': '0', 'rating': '8.6', 'votes': '41049', 'title': 'Lawrence of Arabia '},
   {'seen': '0', 'rating': '7.7', 'votes': '40989', 'title': 'Butterfly Effect, The '},
   {'seen': '0', 'rating': '8', 'votes': '40684', 'title': 'Brazil '},
   {'seen': '0', 'rating': '8.5', 'votes': '40191', 'title': 'Sen to Chihiro no kamikakushi '},
   {'seen': '0', 'rating': '7.1', 'votes': '39903', 'title': 'Superman Returns '},
   {'seen': '0', 'rating': '7.5', 'votes': '39729', 'title': 'Jackie Brown '},
   {'seen': '0', 'rating': '7.5', 'votes': '39636', 'title': 'Chasing Amy '},
   {'seen': '0', 'rating': '7.6', 'votes': '39614', 'title': 'Ghost Busters '},
   {'seen': '0', 'rating': '7.3', 'votes': '39510', 'title': 'Three Kings '},
   {'seen': '0', 'rating': '7.9', 'votes': '39474', 'title': 'Casino '},
   {'seen': '0', 'rating': '7.1', 'votes': '39364', 'title': 'True Lies '},
   {'seen': '0', 'rating': '7.1', 'votes': '39165', 'title': 'Back to the Future Part II '},
   {'seen': '0', 'rating': '6.7', 'votes': '39017', 'title': 'Dumb & Dumber '},
   {'seen': '0', 'rating': '8.1', 'votes': '38930', 'title': 'Deer Hunter, The '},
   {'seen': '0', 'rating': '3.5', 'votes': '38898', 'title': 'Batman & Robin '},
   {'seen': '0', 'rating': '8', 'votes': '38766', 'title': 'Gone with the Wind '},
   {'seen': '0', 'rating': '7.7', 'votes': '38751', 'title': 'Office Space '},
   {'seen': '0', 'rating': '7.6', 'votes': '38498', 'title': 'High Fidelity '},
   {'seen': '0', 'rating': '6.7', 'votes': '38468', 'title': 'Patriot, The '},
   {'seen': '0', 'rating': '8.1', 'votes': '38304', 'title': 'Ying xiong '},
   {'seen': '0', 'rating': '7.9', 'votes': '38228', 'title': 'Insider, The '},
   {'seen': '0', 'rating': '6.2', 'votes': '38005', 'title': 'Day After Tomorrow, The '},
   {'seen': '0', 'rating': '8.1', 'votes': '37993', 'title': 'Finding Neverland '},
   {'seen': '0', 'rating': '8.5', 'votes': '37943', 'title': 'Boot, Das '},
   {'seen': '0', 'rating': '8.1', 'votes': '37916', 'title': 'Graduate, The '},
   {'seen': '0', 'rating': '8.4', 'votes': '37841', 'title': 'Raging Bull '},
   {'seen': '0', 'rating': '6.8', 'votes': '37627', 'title': 'From Dusk Till Dawn '},
   {'seen': '0', 'rating': '6.3', 'votes': '37521', 'title': 'Hannibal '},
   {'seen': '0', 'rating': '7.8', 'votes': '37477', 'title': 'Dances with Wolves '},
   {'seen': '0', 'rating': '5.6', 'votes': '37278', 'title': 'Lost World: Jurassic Park, The '},
   {'seen': '0', 'rating': '5.5', 'votes': '37171', 'title': 'Planet of the Apes '},
   {'seen': '0', 'rating': '7', 'votes': '37056', 'title': 'Napoleon Dynamite '},
   {'seen': '0', 'rating': '6.5', 'votes': '37043', 'title': 'Mr. & Mrs. Smith '},
   {'seen': '0', 'rating': '7.2', 'votes': '36504', 'title': 'Interview with the Vampire: The Vampire Chronicles '},
   {'seen': '0', 'rating': '6.4', 'votes': '36479', 'title': 'Bruce Almighty '},
   {'seen': '0', 'rating': '7.8', 'votes': '36464', 'title': 'Blues Brothers, The '},
   {'seen': '0', 'rating': '7.6', 'votes': '36408', 'title': 'Game, The '},
   {'seen': '0', 'rating': '7.1', 'votes': '36211', 'title': "Devil's Advocate, The "},
   {'seen': '0', 'rating': '6.1', 'votes': '36137', 'title': 'Mars Attacks! '},
   {'seen': '0', 'rating': '7.9', 'votes': '36096', 'title': 'Sideways '},
   {'seen': '0', 'rating': '6.9', 'votes': '36054', 'title': 'Notting Hill '},
   {'seen': '0', 'rating': '7.6', 'votes': '35973', 'title': 'Boogie Nights '},
   {'seen': '0', 'rating': '7', 'votes': '35789', 'title': 'I, Robot '},
   {'seen': '0', 'rating': '7.3', 'votes': '35735', 'title': '28 Days Later... '},
   {'seen': '0', 'rating': '6.4', 'votes': '35724', 'title': 'Con Air '},
   {'seen': '0', 'rating': '7.8', 'votes': '35703', 'title': 'Love Actually '},
   {'seen': '0', 'rating': '7.9', 'votes': '35635', 'title': 'Shaun of the Dead '},
   {'seen': '0', 'rating': '7.8', 'votes': '35576', 'title': '21 Grams '},
   {'seen': '0', 'rating': '7.8', 'votes': '35527', 'title': 'True Romance '},
   {'seen': '0', 'rating': '7.6', 'votes': '35459', 'title': 'Gattaca '},
   {'seen': '0', 'rating': '7.5', 'votes': '35400', 'title': 'Predator '},
   {'seen': '0', 'rating': '5.9', 'votes': '35335', 'title': 'Twister '},
   {'seen': '0', 'rating': '8.5', 'votes': '35311', 'title': 'Chinatown '},
   {'seen': '0', 'rating': '6.5', 'votes': '34915', 'title': 'Cruel Intentions '},
   {'seen': '0', 'rating': '7.3', 'votes': '34860', 'title': 'Wedding Crashers '},
   {'seen': '0', 'rating': '7.8', 'votes': '34552', 'title': 'Adaptation. '},
   {'seen': '0', 'rating': '7.3', 'votes': '34449', 'title': 'Ice Age '},
   {'seen': '0', 'rating': '7.3', 'votes': '34335', 'title': 'Total Recall '},
   {'seen': '0', 'rating': '6.8', 'votes': '34259', 'title': 'Natural Born Killers '},
   {'seen': '0', 'rating': '7.1', 'votes': '34257', 'title': 'Die Hard: With a Vengeance '},
   {'seen': '0', 'rating': '6.8', 'votes': '34234', 'title': 'Back to the Future Part III '},
   {'seen': '0', 'rating': '5.7', 'votes': '34156', 'title': 'Gone in Sixty Seconds '},
   {'seen': '0', 'rating': '7.4', 'votes': '34012', 'title': 'Godfather: Part III, The '},
   {'seen': '0', 'rating': '7.7', 'votes': '33893', 'title': 'Breakfast Club, The '},
   {'seen': '0', 'rating': '6.6', 'votes': '33789', 'title': 'Batman Returns '},
   {'seen': '0', 'rating': '7.9', 'votes': '33769', 'title': 'JFK '},
   {'seen': '0', 'rating': '8.3', 'votes': '33754', 'title': 'Some Like It Hot '},
   {'seen': '0', 'rating': '6.9', 'votes': '33700', 'title': 'American Psycho '},
   {'seen': '0', 'rating': '5.4', 'votes': '33681', 'title': 'Batman Forever '},
   {'seen': '0', 'rating': '7.1', 'votes': '33630', 'title': 'Talented Mr. Ripley, The '},
   {'seen': '0', 'rating': '7.3', 'votes': '33551', 'title': 'Thin Red Line, The '},
   {'seen': '0', 'rating': '8.1', 'votes': '33456', 'title': 'Walk the Line '},
   {'seen': '0', 'rating': '7.6', 'votes': '33404', 'title': 'Aviator, The '},
   {'seen': '0', 'rating': '7.3', 'votes': '33272', 'title': 'Fear and Loathing in Las Vegas '},
   {'seen': '0', 'rating': '6.2', 'votes': '33271', 'title': 'Air Force One '},
   {'seen': '0', 'rating': '7.4', 'votes': '33212', 'title': 'Bourne Supremacy, The '},
   {'seen': '0', 'rating': '7.8', 'votes': '33171', 'title': 'Close Encounters of the Third Kind '},
   {'seen': '0', 'rating': '7.8', 'votes': '33114', 'title': 'Beauty and the Beast '},
   {'seen': '0', 'rating': '7.5', 'votes': '32926', 'title': 'Hunt for Red October, The '},
   {'seen': '0', 'rating': '5.6', 'votes': '32877', 'title': "Charlie's Angels "},
   {'seen': '0', 'rating': '7.5', 'votes': '32817', 'title': 'Few Good Men, A '},
   {'seen': '0', 'rating': '6.8', 'votes': '32708', 'title': 'Blade '},
   {'seen': '0', 'rating': '6.8', 'votes': '32536', 'title': 'Jay and Silent Bob Strike Back '},
   {'seen': '0', 'rating': '6.9', 'votes': '32447', 'title': 'Panic Room '},
   {'seen': '0', 'rating': '7.8', 'votes': '32415', 'title': 'Rocky '},
   {'seen': '0', 'rating': '8', 'votes': '32386', 'title': 'Ed Wood '},
   {'seen': '0', 'rating': '7.7', 'votes': '32381', 'title': 'Boondock Saints, The '},
   {'seen': '0', 'rating': '6.9', 'votes': '32360', 'title': "Bridget Jones's Diary "},
   {'seen': '0', 'rating': '6', 'votes': '32307', 'title': 'Alien: Resurrection '},
   {'seen': '0', 'rating': '6.2', 'votes': '32269', 'title': 'Austin Powers in Goldmember '},
   {'seen': '0', 'rating': '7.3', 'votes': '32091', 'title': 'About Schmidt '},
   {'seen': '0', 'rating': '7.3', 'votes': '32088', 'title': 'Training Day '},
   {'seen': '0', 'rating': '7.7', 'votes': '31707', 'title': 'Equilibrium '},
   {'seen': '0', 'rating': '8.3', 'votes': '31698', 'title': 'Sting, The '},
   {'seen': '0', 'rating': '6.6', 'votes': '31562', 'title': 'Pretty Woman '},
   {'seen': '0', 'rating': '6', 'votes': '31436', 'title': 'Mummy Returns, The '},
   {'seen': '0', 'rating': '5.7', 'votes': '31431', 'title': 'Scary Movie '},
   {'seen': '0', 'rating': '6.2', 'votes': '31148', 'title': 'American Pie 2 '},
   {'seen': '0', 'rating': '7.1', 'votes': '31139', 'title': 'English Patient, The '},
   {'seen': '0', 'rating': '7.8', 'votes': '31110', 'title': 'Airplane! '},
   {'seen': '0', 'rating': '6.5', 'votes': '31088', 'title': 'Analyze This '},
   {'seen': '0', 'rating': '7.6', 'votes': '31088', 'title': 'Dark City '},
   {'seen': '0', 'rating': '6.1', 'votes': '31014', 'title': 'Perfect Storm, The '},
   {'seen': '0', 'rating': '6.3', 'votes': '30965', 'title': 'World Is Not Enough, The '},
   {'seen': '0', 'rating': '6.7', 'votes': '30915', 'title': 'Die Hard 2 '},
   {'seen': '0', 'rating': '6.5', 'votes': '30911', 'title': 'Liar Liar '},
   {'seen': '0', 'rating': '7', 'votes': '30852', 'title': 'Kingdom of Heaven '},
   {'seen': '0', 'rating': '7.6', 'votes': '30850', 'title': 'Aladdin '},
   {'seen': '0', 'rating': '7.4', 'votes': '30757', 'title': 'Chicken Run '},
   {'seen': '0', 'rating': '6.9', 'votes': '30623', 'title': 'Island, The '},
   {'seen': '0', 'rating': '7.7', 'votes': '30595', 'title': 'Fish Called Wanda, A '},
   {'seen': '0', 'rating': '7.2', 'votes': '30588', 'title': 'Erin Brockovich '},
   {'seen': '0', 'rating': '7.3', 'votes': '30519', 'title': 'Phone Booth '},
   {'seen': '0', 'rating': '7.5', 'votes': '30482', 'title': 'Master and Commander: The Far Side of the World '},
   {'seen': '0', 'rating': '6.5', 'votes': '30442', 'title': 'Home Alone '},
   {'seen': '0', 'rating': '6.9', 'votes': '30406', 'title': 'GoldenEye '},
   {'seen': '0', 'rating': '6.2', 'votes': '30400', 'title': 'Die Another Day '},
   {'seen': '0', 'rating': '7', 'votes': '30383', 'title': 'Enemy of the State '},
   {'seen': '0', 'rating': '7.6', 'votes': '30358', 'title': 'History of Violence, A '},
   {'seen': '0', 'rating': '7.9', 'votes': '30337', 'title': 'Nightmare Before Christmas, The '},
   {'seen': '0', 'rating': '7.2', 'votes': '30327', 'title': 'Insomnia '},
   {'seen': '0', 'rating': '6.5', 'votes': '30239', 'title': 'Constantine '},
   {'seen': '0', 'rating': '7.4', 'votes': '30204', 'title': 'Closer '},
   {'seen': '0', 'rating': '7.6', 'votes': '30135', 'title': 'When Harry Met Sally... '},
   {'seen': '0', 'rating': '6', 'votes': '30036', 'title': "Ocean's Twelve "},
   {'seen': '0', 'rating': '5.5', 'votes': '29926', 'title': 'Men in Black II '},
   {'seen': '0', 'rating': '6.4', 'votes': '29875', 'title': 'Mask, The '},
   {'seen': '0', 'rating': '5.9', 'votes': '29768', 'title': 'Hulk '},
   {'seen': '0', 'rating': '8', 'votes': '29715', 'title': 'Young Frankenstein '},
   {'seen': '0', 'rating': '5.3', 'votes': '29705', 'title': 'Van Helsing '},
   {'seen': '0', 'rating': '7.1', 'votes': '29649', 'title': 'Mallrats '},
   {'seen': '0', 'rating': '8.5', 'votes': '29591', 'title': 'Hotel Rwanda '},
   {'seen': '0', 'rating': '6.8', 'votes': '29570', 'title': 'Grease '},
   {'seen': '0', 'rating': '5.7', 'votes': '29551', 'title': 'Fast and the Furious, The '},
   {'seen': '0', 'rating': '8.2', 'votes': '29533', 'title': 'Annie Hall '},
   {'seen': '0', 'rating': '6.8', 'votes': '29532', 'title': 'Romeo + Juliet '},
   {'seen': '0', 'rating': '8.4', 'votes': '29508', 'title': 'Bridge on the River Kwai, The '},
   {'seen': '0', 'rating': '6.3', 'votes': '29506', 'title': 'Alien'},
   {'seen': '0', 'rating': '7.8', 'votes': '29499', 'title': 'Munich '},
   {'seen': '0', 'rating': '7.3', 'votes': '29431', 'title': 'Red Dragon '},
   {'seen': '0', 'rating': '7.4', 'votes': '29342', 'title': 'Star Trek: First Contact '},
   {'seen': '0', 'rating': '5.6', 'votes': '29296', 'title': 'Daredevil '},
   {'seen': '0', 'rating': '4.4', 'votes': '29292', 'title': 'Godzilla '},
   {'seen': '0', 'rating': '7.7', 'votes': '29260', 'title': 'Rushmore '},
   {'seen': '0', 'rating': '7.1', 'votes': '29224', 'title': 'Terminal, The '},
   {'seen': '0', 'rating': '7', 'votes': '29218', 'title': 'Ronin '},
   {'seen': '0', 'rating': '7.2', 'votes': '29161', 'title': 'Galaxy Quest '},
   {'seen': '0', 'rating': '7.3', 'votes': '29047', 'title': "Bug's Life, A "},
   {'seen': '0', 'rating': '7.5', 'votes': '29037', 'title': 'Army of Darkness '},
   {'seen': '0', 'rating': '5.2', 'votes': '28897', 'title': 'Lara Croft: Tomb Raider '},
   {'seen': '0', 'rating': '6.8', 'votes': '28887', 'title': 'National Treasure '},
   {'seen': '0', 'rating': '5.8', 'votes': '28872', 'title': 'Deep Impact '},
   {'seen': '0', 'rating': '7.4', 'votes': '28862', 'title': '40 Year Old Virgin, The '},
   {'seen': '0', 'rating': '7.5', 'votes': '28814', 'title': 'Pleasantville '},
   {'seen': '0', 'rating': '5.6', 'votes': '28615', 'title': 'Jurassic Park III '},
   {'seen': '0', 'rating': '8.3', 'votes': '28579', 'title': 'Mononoke-hime '},
   {'seen': '0', 'rating': '6.7', 'votes': '28486', 'title': "Hitchhiker's Guide to the Galaxy, The "},
   {'seen': '0', 'rating': '7.6', 'votes': '28484', 'title': 'Donnie Brasco '},
   {'seen': '0', 'rating': '6.3', 'votes': '28329', 'title': 'Ace Ventura: Pet Detective '},
   {'seen': '0', 'rating': '6', 'votes': '28313', 'title': 'Me, Myself & Irene '},
   {'seen': '0', 'rating': '8.3', 'votes': '28214', 'title': 'Once Upon a Time in America '},
   {'seen': '0', 'rating': '7.9', 'votes': '28196', 'title': 'This Is Spinal Tap '},
   {'seen': '0', 'rating': '6.8', 'votes': '28181', 'title': 'Italian Job, The '},
   {'seen': '0', 'rating': '6.8', 'votes': '28170', 'title': 'My Big Fat Greek Wedding '},
   {'seen': '0', 'rating': '8.1', 'votes': '28135', 'title': 'Glory '},
   {'seen': '0', 'rating': '7.2', 'votes': '28095', 'title': 'Blow '},
   {'seen': '0', 'rating': '7.1', 'votes': '28007', 'title': 'Beetle Juice '},
   {'seen': '0', 'rating': '8.2', 'votes': '27876', 'title': 'Ben-Hur '},
   {'seen': '0', 'rating': '6.1', 'votes': '27855', 'title': 'Zoolander '},
   {'seen': '0', 'rating': '8.3', 'votes': '27849', 'title': 'Oldboy '},
   {'seen': '0', 'rating': '7.4', 'votes': '27834', 'title': 'Who Framed Roger Rabbit '},
   {'seen': '0', 'rating': '7.2', 'votes': '27791', 'title': 'Team America: World Police '},
   {'seen': '0', 'rating': '7.5', 'votes': '27789', 'title': 'Man on Fire '},
   {'seen': '0', 'rating': '8.4', 'votes': '27761', 'title': 'Great Escape, The '},
   {'seen': '0', 'rating': '6.5', 'votes': '27685', 'title': 'Underworld '},
   {'seen': '0', 'rating': '6.2', 'votes': '27524', 'title': 'Swordfish '},
   {'seen': '0', 'rating': '7.7', 'votes': '27426', 'title': 'Sound of Music, The '},
   {'seen': '0', 'rating': '7.4', 'votes': '27380', 'title': 'Crow, The '},
   {'seen': '0', 'rating': '7.3', 'votes': '27344', 'title': 'Chocolat '},
   {'seen': '0', 'rating': '8.4', 'votes': '27296', 'title': "Singin' in the Rain "},
   {'seen': '0', 'rating': '7.1', 'votes': '27293', 'title': 'Dracula '},
   {'seen': '0', 'rating': '7.4', 'votes': '27284', 'title': 'Abyss, The '},
   {'seen': '0', 'rating': '7.9', 'votes': '27284', 'title': 'Planet of the Apes '},
   {'seen': '0', 'rating': '5.9', 'votes': '27252', 'title': 'Hook '},
   {'seen': '0', 'rating': '6.2', 'votes': '27157', 'title': 'Resident Evil '},
   {'seen': '0', 'rating': '8.7', 'votes': '27125', 'title': "C'era una volta il West "},
   {'seen': '0', 'rating': '8.1', 'votes': '27116', 'title': 'Butch Cassidy and the Sundance Kid '},
   {'seen': '0', 'rating': '9.6', 'votes': '27089', 'title': 'Band of Brothers '},
   {'seen': '0', 'rating': '6.5', 'votes': '27014', 'title': 'Robin Hood: Prince of Thieves '},
   {'seen': '0', 'rating': '5.8', 'votes': '26998', 'title': 'Scream 2 '},
   {'seen': '0', 'rating': '8', 'votes': '26917', 'title': 'Thing, The '},
   {'seen': '0', 'rating': '7.3', 'votes': '26791', 'title': 'Identity '},
   {'seen': '0', 'rating': '7.3', 'votes': '26762', 'title': 'Dawn of the Dead '},
   {'seen': '0', 'rating': '8.5', 'votes': '26713', 'title': 'Untergang, Der '},
   {'seen': '0', 'rating': '6.5', 'votes': '26689', 'title': 'Mrs. Doubtfire '},
   {'seen': '0', 'rating': '7.8', 'votes': '26666', 'title': 'Birds, The '},
   {'seen': '0', 'rating': '7.5', 'votes': '26649', 'title': 'Pi '},
   {'seen': '0', 'rating': '6.3', 'votes': '26626', 'title': 'What Women Want '},
   {'seen': '0', 'rating': '8', 'votes': '26611', 'title': 'Christmas Story, A '},
   {'seen': '0', 'rating': '6.7', 'votes': '26583', 'title': 'Spaceballs '},
   {'seen': '0', 'rating': '6.6', 'votes': '26575', 'title': '10 Things I Hate About You '},
   {'seen': '0', 'rating': '6.4', 'votes': '26562', 'title': 'Meet the Fockers '},
   {'seen': '0', 'rating': '6.2', 'votes': '26559', 'title': "You've Got Mail "},
   {'seen': '0', 'rating': '7.3', 'votes': '26538', 'title': 'Enemy at the Gates '},
   {'seen': '0', 'rating': '6.7', 'votes': '26478', 'title': 'Basic Instinct '},
   {'seen': '0', 'rating': '6.6', 'votes': '26440', 'title': 'Dodgeball: A True Underdog Story '},
   {'seen': '0', 'rating': '7.3', 'votes': '26401', 'title': 'Man on the Moon '},
   {'seen': '0', 'rating': '6.5', 'votes': '26271', 'title': 'What Lies Beneath '},
   {'seen': '0', 'rating': '7.2', 'votes': '26224', 'title': 'Goonies, The '},
   {'seen': '0', 'rating': '7.6', 'votes': '26221', 'title': 'Field of Dreams '},
   {'seen': '0', 'rating': '7.8', 'votes': '26204', 'title': 'Halloween '},
   {'seen': '0', 'rating': '7.4', 'votes': '26165', 'title': 'Lethal Weapon '},
   {'seen': '0', 'rating': '7.2', 'votes': '26151', 'title': 'Full Monty, The '},
   {'seen': '0', 'rating': '8', 'votes': '26144', 'title': 'Sling Blade '},
   {'seen': '0', 'rating': '7', 'votes': '26118', 'title': 'Saw II '},
   {'seen': '0', 'rating': '6', 'votes': '26072', 'title': 'Fantastic Four '},
   {'seen': '0', 'rating': '6.4', 'votes': '25959', 'title': 'Any Given Sunday '},
   {'seen': '0', 'rating': '8.4', 'votes': '25803', 'title': 'Maltese Falcon, The '},
   {'seen': '0', 'rating': '7.4', 'votes': '25795', 'title': 'About a Boy '},
   {'seen': '0', 'rating': '4', 'votes': '25760', 'title': 'Wild Wild West '},
   {'seen': '0', 'rating': '6.5', 'votes': '25681', 'title': 'Anchorman: The Legend of Ron Burgundy '},
   {'seen': '0', 'rating': '5.4', 'votes': '25551', 'title': 'Waterworld '},
   {'seen': '0', 'rating': '7.7', 'votes': '25527', 'title': 'Blue Velvet '},
   {'seen': '0', 'rating': '7.3', 'votes': '25500', 'title': 'School of Rock, The '},
   {'seen': '0', 'rating': '6.7', 'votes': '25424', 'title': '8 Mile '},
   {'seen': '0', 'rating': '5.5', 'votes': '25413', 'title': 'xXx '},
   {'seen': '0', 'rating': '6.7', 'votes': '25243', 'title': 'Wedding Singer, The '},
   {'seen': '0', 'rating': '7.3', 'votes': '25231', 'title': 'Go '},
   {'seen': '0', 'rating': '7.2', 'votes': '25226', 'title': 'Life Aquatic with Steve Zissou, The '},
   {'seen': '0', 'rating': '7.4', 'votes': '25203', 'title': 'Snakes on a Plane '},
   {'seen': '0', 'rating': '8.5', 'votes': '25155', 'title': 'Third Man, The '},
   {'seen': '0', 'rating': '5.4', 'votes': '25151', 'title': 'AVP: Alien vs. Predator '},
   {'seen': '0', 'rating': '7.5', 'votes': '25146', 'title': 'Inside Man '},
   {'seen': '0', 'rating': '6.7', 'votes': '25145', 'title': 'Pitch Black '},
   {'seen': '0', 'rating': '6.8', 'votes': '25045', 'title': 'Ghost '},
   {'seen': '0', 'rating': '7.8', 'votes': '24984', 'title': 'Goldfinger '},
   {'seen': '0', 'rating': '7.5', 'votes': '24951', 'title': 'Raising Arizona '},
   {'seen': '0', 'rating': '7.7', 'votes': '24931', 'title': 'Lord of War '},
   {'seen': '0', 'rating': '7.4', 'votes': '24901', 'title': 'Grosse Pointe Blank '},
   {'seen': '0', 'rating': '7.2', 'votes': '24900', 'title': 'Virgin Suicides, The '},
   {'seen': '0', 'rating': '7.2', 'votes': '24865', 'title': 'Superman '},
   {'seen': '0', 'rating': '5.9', 'votes': '24752', 'title': 'Big Daddy '},
   {'seen': '0', 'rating': '7.4', 'votes': '24703', 'title': 'Punch-Drunk Love '},
   {'seen': '0', 'rating': '6', 'votes': '24690', 'title': '8MM '},
   {'seen': '0', 'rating': '7.2', 'votes': '24656', 'title': 'Negotiator, The '},
   {'seen': '0', 'rating': '5.4', 'votes': '24606', 'title': 'Alexander '},
   {'seen': '0', 'rating': '6.7', 'votes': '24596', 'title': 'Happy Gilmore '},
   {'seen': '0', 'rating': '6.7', 'votes': '24581', 'title': 'Mask of Zorro, The '},
   {'seen': '0', 'rating': '6.7', 'votes': '24533', 'title': 'From Hell '},
   {'seen': '0', 'rating': '7.7', 'votes': '24531', 'title': 'Willy Wonka & the Chocolate Factory '},
   {'seen': '0', 'rating': '6.4', 'votes': '24524', 'title': 'Tomorrow Never Dies '},
   {'seen': '0', 'rating': '7.5', 'votes': '24416', 'title': 'Philadelphia '},
   {'seen': '0', 'rating': '7.9', 'votes': '24386', 'title': 'Dogville '},
   {'seen': '0', 'rating': '7.8', 'votes': '24372', 'title': 'Ghost World '},
   {'seen': '0', 'rating': '8', 'votes': '24254', 'title': 'Notebook, The '},
   {'seen': '0', 'rating': '6.6', 'votes': '24253', 'title': 'Rush Hour '},
   {'seen': '0', 'rating': '6.6', 'votes': '24239', 'title': 'Sleepless in Seattle '},
   {'seen': '0', 'rating': '7.2', 'votes': '24228', 'title': 'Big '},
   {'seen': '0', 'rating': '7.1', 'votes': '24167', 'title': 'Sleepers '},
   {'seen': '0', 'rating': '7.1', 'votes': '24024', 'title': 'K-PAX '},
   {'seen': '0', 'rating': '7.3', 'votes': '24013', 'title': 'Cold Mountain '},
   {'seen': '0', 'rating': '6.8', 'votes': '24000', 'title': 'Desperado '},
   {'seen': '0', 'rating': '7.4', 'votes': '23978', 'title': 'Cider House Rules, The '},
   {'seen': '0', 'rating': '7.8', 'votes': '23945', 'title': '25th Hour '},
   {'seen': '0', 'rating': '6.6', 'votes': '23923', 'title': 'Meet Joe Black '},
   {'seen': '0', 'rating': '6.8', 'votes': '23851', 'title': 'Mission: Impossible III '},
   {'seen': '0', 'rating': '6.5', 'votes': '23809', 'title': 'Blade II '},
   {'seen': '0', 'rating': '6.2', 'votes': '23809', 'title': 'Bone Collector, The '},
   {'seen': '0', 'rating': '6', 'votes': '23799', 'title': 'Entrapment '},
   {'seen': '0', 'rating': '8.1', 'votes': '23741', 'title': 'Cinderella Man '},
   {'seen': '0', 'rating': '6.6', 'votes': '23695', 'title': 'Final Destination '},
   {'seen': '0', 'rating': '6.1', 'votes': '23618', 'title': 'King Arthur '},
   {'seen': '0', 'rating': '8.1', 'votes': '23467', 'title': 'Amores perros '},
   {'seen': '0', 'rating': '7.3', 'votes': '23430', 'title': 'Jarhead '},
   {'seen': '0', 'rating': '6.3', 'votes': '23420', 'title': 'Legally Blonde '},
   {'seen': '0', 'rating': '6.5', 'votes': '23389', 'title': 'Silent Hill '},
   {'seen': '0', 'rating': '6.8', 'votes': '23358', 'title': 'Old School '},
   {'seen': '0', 'rating': '5.2', 'votes': '23345', 'title': 'End of Days '},
   {'seen': '0', 'rating': '6.8', 'votes': '23345', 'title': 'Payback '},
   {'seen': '0', 'rating': '6.6', 'votes': '23336', 'title': 'Hellboy '},
   {'seen': '0', 'rating': '8.6', 'votes': '23288', 'title': 'Sunset Blvd. '},
   {'seen': '0', 'rating': '7', 'votes': '23282', 'title': 'One Hour Photo '},
   {'seen': '0', 'rating': '5.5', 'votes': '23235', 'title': 'Deep Blue Sea '},
   {'seen': '0', 'rating': '7.5', 'votes': '23157', 'title': 'Animal House '},
   {'seen': '0', 'rating': '7.2', 'votes': '23154', 'title': 'Thelma & Louise '},
   {'seen': '0', 'rating': '8.3', 'votes': '23152', 'title': 'Elephant Man, The '},
   {'seen': '0', 'rating': '6.8', 'votes': '23096', 'title': '50 First Dates '},
   {'seen': '0', 'rating': '6.4', 'votes': '23079', 'title': 'Ninth Gate, The '},
   {'seen': '0', 'rating': '8', 'votes': '23065', 'title': 'Spartacus '},
   {'seen': '0', 'rating': '7.6', 'votes': '23047', 'title': 'Hours, The '},
   {'seen': '0', 'rating': '7.2', 'votes': '23033', 'title': 'Out of Sight '},
   {'seen': '0', 'rating': '7.7', 'votes': '22971', 'title': 'Blazing Saddles '},
   {'seen': '0', 'rating': '6.3', 'votes': '22965', 'title': 'Lethal Weapon 4 '},
   {'seen': '0', 'rating': '7.5', 'votes': '22916', 'title': 'Leaving Las Vegas '},
   {'seen': '0', 'rating': '7', 'votes': '22834', 'title': 'Girl, Interrupted '},
   {'seen': '0', 'rating': '6.5', 'votes': '22771', 'title': 'Whole Nine Yards, The '},
   {'seen': '0', 'rating': '6.4', 'votes': '22767', 'title': 'Rush Hour 2 '},
   {'seen': '0', 'rating': '7.6', 'votes': '22754', 'title': "What's Eating Gilbert Grape "},
   {'seen': '0', 'rating': '7.5', 'votes': '22735', 'title': 'Scent of a Woman '},
   {'seen': '0', 'rating': '7.1', 'votes': '22720', 'title': 'Highlander '},
   {'seen': '0', 'rating': '7.5', 'votes': '22641', 'title': 'Cube '},
   {'seen': '0', 'rating': '6.4', 'votes': '22540', 'title': 'Stargate '},
   {'seen': '0', 'rating': '6.8', 'votes': '22473', 'title': 'Hitch '},
   {'seen': '0', 'rating': '5.4', 'votes': '22468', 'title': 'League of Extraordinary Gentlemen, The '},
   {'seen': '0', 'rating': '5.6', 'votes': '22431', 'title': 'Cable Guy, The '},
   {'seen': '0', 'rating': '7.1', 'votes': '22404', 'title': 'Four Weddings and a Funeral '},
   {'seen': '0', 'rating': '6.8', 'votes': '22385', 'title': 'Rocky Horror Picture Show, The '},
   {'seen': '0', 'rating': '7.4', 'votes': '22363', 'title': 'Election '},
   {'seen': '0', 'rating': '6.9', 'votes': '22359', 'title': 'Spy Game '},
   {'seen': '0', 'rating': '6.6', 'votes': '22319', 'title': 'Wild Things '},
   {'seen': '0', 'rating': '6.1', 'votes': '22181', 'title': 'Once Upon a Time in Mexico '},
   {'seen': '0', 'rating': '6.6', 'votes': '22153', 'title': 'Thomas Crown Affair, The '},
   {'seen': '0', 'rating': '7.5', 'votes': '22140', 'title': 'Tombstone '},
   {'seen': '0', 'rating': '6.7', 'votes': '22138', 'title': "Wayne's World "},
   {'seen': '0', 'rating': '8.1', 'votes': '22127', 'title': 'Dog Day Afternoon '},
   {'seen': '0', 'rating': '6.7', 'votes': '22069', 'title': 'X Files, The '},
   {'seen': '0', 'rating': '7.6', 'votes': '22065', 'title': 'Billy Elliot '},
   {'seen': '0', 'rating': '6.5', 'votes': '22030', 'title': 'Ransom '},
   {'seen': '0', 'rating': '7.7', 'votes': '21972', 'title': "Man Who Wasn't There, The "},
   {'seen': '0', 'rating': '6.2', 'votes': '21958', 'title': 'Miss Congeniality '},
   {'seen': '0', 'rating': '7.2', 'votes': '21948', 'title': 'Beverly Hills Cop '},
   {'seen': '0', 'rating': '7.4', 'votes': '21836', 'title': 'Phantom of the Opera, The '},
   {'seen': '0', 'rating': '7.8', 'votes': '21835', 'title': 'Match Point '},
   {'seen': '0', 'rating': '6.3', 'votes': '21828', 'title': 'Secret Window '},
   {'seen': '0', 'rating': '7.7', 'votes': '21794', 'title': 'Constant Gardener, The '},
   {'seen': '0', 'rating': '7.1', 'votes': '21785', 'title': 'Arlington Road '},
   {'seen': '0', 'rating': '7', 'votes': '21755', 'title': 'Mean Girls '},
   {'seen': '0', 'rating': '6.4', 'votes': '21686', 'title': 'Dune '},
   {'seen': '0', 'rating': '5.7', 'votes': '21627', 'title': 'Two Weeks Notice '},
   {'seen': '0', 'rating': '5', 'votes': '21595', 'title': 'Ace Ventura: When Nature Calls '},
   {'seen': '0', 'rating': '7.3', 'votes': '21575', 'title': 'RoboCop '},
   {'seen': '0', 'rating': '6', 'votes': '21573', 'title': 'Anger Management '},
   {'seen': '0', 'rating': '8.1', 'votes': '21548', 'title': 'Gandhi '},
   {'seen': '0', 'rating': '7.2', 'votes': '21402', 'title': 'Gosford Park '},
   {'seen': '0', 'rating': '6.4', 'votes': '21375', 'title': 'Bad Boys '},
   {'seen': '0', 'rating': '6.2', 'votes': '21347', 'title': 'Road Trip '},
   {'seen': '0', 'rating': '6.4', 'votes': '21306', 'title': 'Final Fantasy: The Spirits Within '},
   {'seen': '0', 'rating': '7.5', 'votes': '21303', 'title': 'Corpse Bride '},
   {'seen': '0', 'rating': '7.3', 'votes': '21266', 'title': 'Lost Highway '},
   {'seen': '0', 'rating': '7.8', 'votes': '21186', 'title': 'Evil Dead II '},
   {'seen': '0', 'rating': '6.8', 'votes': '21102', 'title': 'Score, The '},
   {'seen': '0', 'rating': '6.1', 'votes': '21099', 'title': 'Jumanji '},
   {'seen': '0', 'rating': '7.1', 'votes': '21091', 'title': 'Cape Fear '},
   {'seen': '0', 'rating': '6.3', 'votes': '21032', 'title': "My Best Friend's Wedding "},
   {'seen': '0', 'rating': '5.8', 'votes': '20942', 'title': 'Hostel '},
   {'seen': '0', 'rating': '5.3', 'votes': '20932', 'title': 'Hollow Man '},
   {'seen': '0', 'rating': '6.6', 'votes': '20921', 'title': 'Clueless '},
   {'seen': '0', 'rating': '7.6', 'votes': '20914', 'title': 'Last of the Mohicans, The '},
   {'seen': '0', 'rating': '5.5', 'votes': '20906', 'title': 'Waterboy, The '},
   {'seen': '0', 'rating': '5.9', 'votes': '20888', 'title': 'Beach, The '},
   {'seen': '0', 'rating': '6.2', 'votes': '20882', 'title': 'American Wedding '},
   {'seen': '0', 'rating': '6.9', 'votes': '20808', 'title': 'Antz '},
   {'seen': '0', 'rating': '6.2', 'votes': '20805', 'title': 'Starsky & Hutch '},
   {'seen': '0', 'rating': '7.3', 'votes': '20725', 'title': 'Babe '},
   {'seen': '0', 'rating': '6.4', 'votes': '20718', 'title': 'Sum of All Fears, The '},
   {'seen': '0', 'rating': '7.2', 'votes': '20715', 'title': 'Bend It Like Beckham '},
   {'seen': '0', 'rating': '7.4', 'votes': '20714', 'title': 'Remember the Titans '},
   {'seen': '0', 'rating': '7.8', 'votes': '20677', 'title': 'Ray '},
   {'seen': '0', 'rating': '7', 'votes': '20653', 'title': 'Wag the Dog '},
   {'seen': '0', 'rating': '6.4', 'votes': '20648', 'title': "Knight's Tale, A "},
   {'seen': '0', 'rating': '7.8', 'votes': '20613', 'title': 'Dancer in the Dark '},
   {'seen': '0', 'rating': '6', 'votes': '20580', 'title': 'Cell, The '},
   {'seen': '0', 'rating': '6.4', 'votes': '20558', 'title': 'Sky Captain and the World of Tomorrow '},
   {'seen': '0', 'rating': '7', 'votes': '20520', 'title': 'We Were Soldiers '},
   {'seen': '0', 'rating': '5.5', 'votes': '20501', 'title': 'Last Action Hero '},
   {'seen': '0', 'rating': '8', 'votes': '20453', 'title': 'Batoru rowaiaru '},
   {'seen': '0', 'rating': '7.4', 'votes': '20433', 'title': 'Matchstick Men '},
   {'seen': '0', 'rating': '7.9', 'votes': '20397', 'title': "Miller's Crossing "},
   {'seen': '0', 'rating': '7.7', 'votes': '20354', 'title': 'Star Trek: The Wrath of Khan '},
   {'seen': '0', 'rating': '5.8', 'votes': '20293', 'title': 'Event Horizon '},
   {'seen': '0', 'rating': '8', 'votes': '20257', 'title': 'Straight Story, The '},
   {'seen': '0', 'rating': '7.6', 'votes': '20235', 'title': "Carlito's Way "},
   {'seen': '0', 'rating': '6.1', 'votes': '20229', 'title': 'Demolition Man '},
   {'seen': '0', 'rating': '7.2', 'votes': '20215', 'title': 'Syriana '},
   {'seen': '0', 'rating': '6.9', 'votes': '20209', 'title': 'Time to Kill, A '},
   {'seen': '0', 'rating': '7.7', 'votes': '20185', 'title': 'Akira '},
   {'seen': '0', 'rating': '5.2', 'votes': '20164', 'title': 'I Know What You Did Last Summer '},
   {'seen': '0', 'rating': '7.6', 'votes': '20145', 'title': 'Swingers '},
   {'seen': '0', 'rating': '5.7', 'votes': '20138', 'title': 'Grudge, The '},
   {'seen': '0', 'rating': '6.1', 'votes': '20120', 'title': 'Bad Boys II '},
   {'seen': '0', 'rating': '5.7', 'votes': '20120', 'title': 'Ghostbusters II '},
   {'seen': '0', 'rating': '7.4', 'votes': '20094', 'title': 'Evil Dead, The '},
   {'seen': '0', 'rating': '8.5', 'votes': '20094', 'title': 'Paths of Glory '},
   {'seen': '0', 'rating': '2.4', 'votes': '20087', 'title': 'Battlefield Earth: A Saga of the Year 3000 '},
   {'seen': '0', 'rating': '7.3', 'votes': '20084', 'title': 'Falling Down '},
   {'seen': '0', 'rating': '7.2', 'votes': '20005', 'title': "Monster's Ball "},
   {'seen': '0', 'rating': '5.3', 'votes': '19989', 'title': 'Scream 3 '},
   {'seen': '0', 'rating': '6.2', 'votes': '19982', 'title': 'City of Angels '},
   {'seen': '0', 'rating': '4.8', 'votes': '19915', 'title': "Charlie's Angels: Full Throttle "},
   {'seen': '0', 'rating': '6.8', 'votes': '19895', 'title': 'Gremlins '},
   {'seen': '0', 'rating': '7.8', 'votes': '19858', 'title': 'Iron Giant, The '},
   {'seen': '0', 'rating': '5.9', 'votes': '19852', 'title': 'Dirty Dancing '},
   {'seen': '0', 'rating': '6.9', 'votes': '19843', 'title': "Lemony Snicket's A Series of Unfortunate Events "},
   {'seen': '0', 'rating': '6.9', 'votes': '19832', 'title': 'Lethal Weapon 2 '},
   {'seen': '0', 'rating': '6.4', 'votes': '19765', 'title': 'Conspiracy Theory '},
   {'seen': '0', 'rating': '7.5', 'votes': '19706', 'title': 'Wonder Boys '},
   {'seen': '0', 'rating': '7.6', 'votes': '19663', 'title': 'Dead Man Walking '},
   {'seen': '0', 'rating': '7.4', 'votes': '19642', 'title': 'Count of Monte Cristo, The '},
   {'seen': '0', 'rating': '6.5', 'votes': '19637', 'title': 'U-571 '},
   {'seen': '0', 'rating': '7.2', 'votes': '19573', 'title': 'Rounders '},
   {'seen': '0', 'rating': '8.4', 'votes': '19563', 'title': 'Nuovo cinema Paradiso '},
   {'seen': '0', 'rating': '6.6', 'votes': '19542', 'title': 'eXistenZ '},
   {'seen': '0', 'rating': '7.3', 'votes': '19522', 'title': 'Frequency '},
   {'seen': '0', 'rating': '7.7', 'votes': '19470', 'title': 'Maquinista, El '},
   {'seen': '0', 'rating': '6.8', 'votes': '19453', 'title': 'Girl Next Door, The '},
   {'seen': '0', 'rating': '7.8', 'votes': '19443', 'title': 'Kung fu '},
   {'seen': '0', 'rating': '8.3', 'votes': '19387', 'title': 'Cool Hand Luke '},
   {'seen': '0', 'rating': '8.1', 'votes': '19387', 'title': 'Patton '},
   {'seen': '0', 'rating': '6.5', 'votes': '19364', 'title': 'Madagascar '},
   {'seen': '0', 'rating': '7.5', 'votes': '19327', 'title': "Boys Don't Cry "},
   {'seen': '0', 'rating': '6.6', 'votes': '19289', 'title': 'Firm, The '},
   {'seen': '0', 'rating': '6.9', 'votes': '19243', 'title': 'Get Shorty '},
   {'seen': '0', 'rating': '6.3', 'votes': '19242', 'title': 'Bowfinger '},
   {'seen': '0', 'rating': '6', 'votes': '19235', 'title': '13th Warrior, The '},
   {'seen': '0', 'rating': '6.2', 'votes': '19229', 'title': 'Chronicles of Riddick, The '},
   {'seen': '0', 'rating': '7.3', 'votes': '19189', 'title': 'Dazed and Confused '},
   {'seen': '0', 'rating': '7.6', 'votes': '19080', 'title': 'Shi mian mai fu '},
   {'seen': '0', 'rating': '5.7', 'votes': '19044', 'title': 'Evolution '},
   {'seen': '0', 'rating': '6.3', 'votes': '19023', 'title': 'Rat Race '},
   {'seen': '0', 'rating': '6.2', 'votes': '18986', 'title': 'Flightplan '},
   {'seen': '0', 'rating': '7.9', 'votes': '18917', 'title': 'Deliverance '},
   {'seen': '0', 'rating': '8', 'votes': '18916', 'title': 'Hable con ella '},
   {'seen': '0', 'rating': '8.4', 'votes': '18866', 'title': 'Manchurian Candidate, The '},
   {'seen': '0', 'rating': '7.8', 'votes': '18815', 'title': 'Dawn of the Dead '},
   {'seen': '0', 'rating': '5.9', 'votes': '18807', 'title': 'S.W.A.T. '},
   {'seen': '0', 'rating': '5.8', 'votes': '18799', 'title': 'Eraser '},
   {'seen': '0', 'rating': '4.5', 'votes': '18726', 'title': 'Haunting, The '},
   {'seen': '0', 'rating': '4.7', 'votes': '18712', 'title': "Dude, Where's My Car? "},
   {'seen': '0', 'rating': '6.5', 'votes': '18705', 'title': 'Recruit, The '},
   {'seen': '0', 'rating': '7.2', 'votes': '18700', 'title': 'Bad Santa '},
   {'seen': '0', 'rating': '4.8', 'votes': '18618', 'title': 'Mission to Mars '},
   {'seen': '0', 'rating': '7.7', 'votes': '18571', 'title': 'Snow White and the Seven Dwarfs '},
   {'seen': '0', 'rating': '4.6', 'votes': '18546', 'title': 'Lost in Space '},
   {'seen': '0', 'rating': '7.4', 'votes': '18542', 'title': 'Monster '},
   {'seen': '0', 'rating': '8.1', 'votes': '18537', 'title': 'Before Sunset '},
   {'seen': '0', 'rating': '6.6', 'votes': '18528', 'title': 'Interpreter, The '},
   {'seen': '0', 'rating': '6.9', 'votes': '18497', 'title': 'League of Their Own, A '},
   {'seen': '0', 'rating': '5.1', 'votes': '18483', 'title': 'Home Alone 2: Lost in New York '},
   {'seen': '0', 'rating': '7.9', 'votes': '18479', 'title': 'Good Night, and Good Luck. '},
   {'seen': '0', 'rating': '5.9', 'votes': '18473', 'title': 'Mexican, The '},
   {'seen': '0', 'rating': '7.7', 'votes': '18464', 'title': 'Y tu mam'},
   {'seen': '0', 'rating': '6.7', 'votes': '18456', 'title': 'Pay It Forward '},
   {'seen': '0', 'rating': '7.5', 'votes': '18420', 'title': 'Simple Plan, A '},
   {'seen': '0', 'rating': '4.5', 'votes': '18405', 'title': 'Maid in Manhattan '},
   {'seen': '0', 'rating': '7.6', 'votes': '18402', 'title': 'Mary Poppins '},
   {'seen': '0', 'rating': '7.4', 'votes': '18365', 'title': 'Ghost Dog: The Way of the Samurai '},
   {'seen': '0', 'rating': '8', 'votes': '18363', 'title': "Rosemary's Baby "},
   {'seen': '0', 'rating': '6.6', 'votes': '18362', 'title': 'Red Eye '},
   {'seen': '0', 'rating': '6.8', 'votes': '18358', 'title': 'Legends of the Fall '},
   {'seen': '0', 'rating': '6.6', 'votes': '18324', 'title': 'Conan the Barbarian '},
   {'seen': '0', 'rating': '7.8', 'votes': '18279', 'title': 'Fantasia '},
   {'seen': '0', 'rating': '7.8', 'votes': '18279', 'title': 'MASH '},
   {'seen': '0', 'rating': '7.2', 'votes': '18260', 'title': 'Finding Forrester '},
   {'seen': '0', 'rating': '6.3', 'votes': '18250', 'title': 'Lethal Weapon 3 '},
   {'seen': '0', 'rating': '5.7', 'votes': '18240', 'title': 'Broken Arrow '},
   {'seen': '0', 'rating': '6', 'votes': '18229', 'title': 'Stigmata '},
   {'seen': '0', 'rating': '7.2', 'votes': '18159', 'title': 'Nightmare on Elm Street, A '},
   {'seen': '0', 'rating': '7.7', 'votes': '18132', 'title': 'Lucky Number Slevin '},
   {'seen': '0', 'rating': '7.8', 'votes': '18114', 'title': 'Pride & Prejudice '},
   {'seen': '0', 'rating': '7.6', 'votes': '18092', 'title': 'Elizabeth '},
   {'seen': '0', 'rating': '8.3', 'votes': '18087', 'title': 'On the Waterfront '},
   {'seen': '0', 'rating': '6.7', 'votes': '18037', 'title': 'Maverick '},
   {'seen': '0', 'rating': '6.6', 'votes': '18035', 'title': 'Coming to America '},
   {'seen': '0', 'rating': '7.1', 'votes': '18019', 'title': 'Crimson Tide '},
   {'seen': '0', 'rating': '7.6', 'votes': '17976', 'title': 'Misery '},
   {'seen': '0', 'rating': '7.2', 'votes': '17952', 'title': 'Caddyshack '},
   {'seen': '0', 'rating': '5.7', 'votes': '17948', 'title': 'Resident Evil: Apocalypse '},
   {'seen': '0', 'rating': '6', 'votes': '17946', 'title': 'Shallow Hal '},
   {'seen': '0', 'rating': '4.3', 'votes': '17930', 'title': 'Scary Movie 2 '},
   {'seen': '0', 'rating': '7.5', 'votes': '17911', 'title': 'Witness '},
   {'seen': '0', 'rating': '5.7', 'votes': '17905', 'title': 'Kindergarten Cop '},
   {'seen': '0', 'rating': '6.6', 'votes': '17896', 'title': 'Bringing Out the Dead '},
   {'seen': '0', 'rating': '8.1', 'votes': '17889', 'title': 'African Queen, The '},
   {'seen': '0', 'rating': '8.5', 'votes': '17874', 'title': 'Wallace & Gromit in The Wrong Trousers '},
   {'seen': '0', 'rating': '6.9', 'votes': '17849', 'title': 'First Blood '},
   {'seen': '0', 'rating': '7.8', 'votes': '17809', 'title': 'Todo sobre mi madre '},
   {'seen': '0', 'rating': '5.7', 'votes': '17808', 'title': 'Mystery Men '},
   {'seen': '0', 'rating': '7.9', 'votes': '17758', 'title': 'Barry Lyndon '},
   {'seen': '0', 'rating': '7.6', 'votes': '17746', 'title': 'Sense and Sensibility '},
   {'seen': '0', 'rating': '6.4', 'votes': '17741', 'title': 'Outbreak '},
   {'seen': '0', 'rating': '7.5', 'votes': '17729', 'title': 'Naked Gun: From the Files of Police Squad!, The '},
   {'seen': '0', 'rating': '8.1', 'votes': '17673', 'title': 'Wallace & Gromit in The Curse of the Were-Rabbit '},
   {'seen': '0', 'rating': '7.1', 'votes': '17655', 'title': 'Good Morning, Vietnam '},
   {'seen': '0', 'rating': '7.9', 'votes': '17617', 'title': "All the President's Men "},
   {'seen': '0', 'rating': '7.9', 'votes': '17603', 'title': 'Midnight Cowboy '},
   {'seen': '0', 'rating': '5.9', 'votes': '17516', 'title': 'Double Jeopardy '},
   {'seen': '0', 'rating': '5.3', 'votes': '17481', 'title': 'Coyote Ugly '},
   {'seen': '0', 'rating': '8.4', 'votes': '17476', 'title': 'All About Eve '},
   {'seen': '0', 'rating': '6.1', 'votes': '17459', 'title': 'Faculty, The '},
   {'seen': '0', 'rating': '7.9', 'votes': '17449', 'title': 'Diarios de motocicleta '},
   {'seen': '0', 'rating': '7.4', 'votes': '17444', 'title': 'Tootsie '},
   {'seen': '0', 'rating': '8', 'votes': '17434', 'title': 'Bonnie and Clyde '},
   {'seen': '0', 'rating': '7.1', 'votes': '17405', 'title': 'Harold & Kumar Go to White Castle '},
   {'seen': '0', 'rating': '5.6', 'votes': '17377', 'title': 'How the Grinch Stole Christmas '},
   {'seen': '0', 'rating': '7.9', 'votes': '17374', 'title': 'Kiss Kiss Bang Bang '},
   {'seen': '0', 'rating': '7.8', 'votes': '17368', 'title': 'Fucking '},
   {'seen': '0', 'rating': '5.9', 'votes': '17360', 'title': 'Shaft '},
   {'seen': '0', 'rating': '7.2', 'votes': '17342', 'title': 'Labyrinth '},
   {'seen': '0', 'rating': '7.8', 'votes': '17323', 'title': 'Night of the Living Dead '},
   {'seen': '0', 'rating': '7.9', 'votes': '17296', 'title': 'Capote '},
   {'seen': '0', 'rating': '8', 'votes': '17198', 'title': 'King Kong '},
   {'seen': '0', 'rating': '7.5', 'votes': '17170', 'title': 'Descent, The '},
   {'seen': '0', 'rating': '8.5', 'votes': '17161', 'title': 'M '},
   {'seen': '0', 'rating': '5.9', 'votes': '17105', 'title': 'Twins '},
   {'seen': '0', 'rating': '5.4', 'votes': '17086', 'title': "She's All That "},
   {'seen': '0', 'rating': '8.5', 'votes': '17052', 'title': 'Metropolis '},
   {'seen': '0', 'rating': '6.2', 'votes': '17030', 'title': 'Punisher, The '},
   {'seen': '0', 'rating': '7', 'votes': '17005', 'title': 'Pacte des loups, Le '},
   {'seen': '0', 'rating': '6.7', 'votes': '16968', 'title': 'Manchurian Candidate, The '},
   {'seen': '0', 'rating': '7.3', 'votes': '16962', 'title': 'Little Mermaid, The '},
   {'seen': '0', 'rating': '5.4', 'votes': '16937', 'title': 'Mr. Deeds '},
   {'seen': '0', 'rating': '6.2', 'votes': '16928', 'title': 'Transporter, The '},
   {'seen': '0', 'rating': '3.3', 'votes': '16923', 'title': 'Speed 2: Cruise Control '},
   {'seen': '0', 'rating': '5.7', 'votes': '16919', 'title': 'Jackal, The '},
   {'seen': '0', 'rating': '6.5', 'votes': '16912', 'title': 'Intolerable Cruelty '},
   {'seen': '0', 'rating': '8', 'votes': '16894', 'title': 'Manhattan '},
   {'seen': '0', 'rating': '7.4', 'votes': '16891', 'title': 'Meaning of Life, The '},
   {'seen': '0', 'rating': '7.5', 'votes': '16872', 'title': 'Primal Fear '},
   {'seen': '0', 'rating': '7.6', 'votes': '16868', 'title': 'October Sky '},
   {'seen': '0', 'rating': '8.5', 'votes': '16839', 'title': 'Rash'},
   {'seen': '0', 'rating': '8.3', 'votes': '16823', 'title': 'Ran '},
   {'seen': '0', 'rating': '7.7', 'votes': '16796', 'title': "Breakfast at Tiffany's "},
   {'seen': '0', 'rating': '6.5', 'votes': '16780', 'title': 'Changing Lanes '},
   {'seen': '0', 'rating': '7.5', 'votes': '16766', 'title': 'American Graffiti '},
   {'seen': '0', 'rating': '6.7', 'votes': '16739', 'title': 'Clear and Present Danger '},
   {'seen': '0', 'rating': '5.3', 'votes': '16710', 'title': 'Sphere '},
   {'seen': '0', 'rating': '7.7', 'votes': '16681', 'title': 'West Side Story '},
   {'seen': '0', 'rating': '7', 'votes': '16667', 'title': 'I Heart Huckabees '},
   {'seen': '0', 'rating': '7.5', 'votes': '16661', 'title': 'Ice Storm, The '},
   {'seen': '0', 'rating': '6.3', 'votes': '16597', 'title': 'Ladykillers, The '},
   {'seen': '0', 'rating': '8.3', 'votes': '16595', 'title': 'High Noon '},
   {'seen': '0', 'rating': '6.3', 'votes': '16595', 'title': 'Solaris '},
   {'seen': '0', 'rating': '7.1', 'votes': '16564', 'title': 'Confessions of a Dangerous Mind '},
   {'seen': '0', 'rating': '6.7', 'votes': '16562', 'title': 'Cop Land '},
   {'seen': '0', 'rating': '6.1', 'votes': '16519', 'title': 'Billy Madison '},
   {'seen': '0', 'rating': '6.6', 'votes': '16510', 'title': 'Land of the Dead '},
   {'seen': '0', 'rating': '7.4', 'votes': '16504', 'title': 'Hudsucker Proxy, The '},
   {'seen': '0', 'rating': '5.3', 'votes': '16441', 'title': 'Runaway Bride '},
   {'seen': '0', 'rating': '7.2', 'votes': '16417', 'title': 'Life of David Gale, The '},
   {'seen': '0', 'rating': '6.6', 'votes': '16408', 'title': 'Bandits '},
   {'seen': '0', 'rating': '5.9', 'votes': '16369', 'title': 'Cliffhanger '},
   {'seen': '0', 'rating': '6.8', 'votes': '16333', 'title': "Something's Gotta Give "},
   {'seen': '0', 'rating': '6.6', 'votes': '16330', 'title': "Bill & Ted's Excellent Adventure "},
   {'seen': '0', 'rating': '6.9', 'votes': '16318', 'title': 'Elf '},
   {'seen': '0', 'rating': '6.7', 'votes': '16315', 'title': 'Gift, The '},
   {'seen': '0', 'rating': '5.4', 'votes': '16314', 'title': 'Rocky IV '},
   {'seen': '0', 'rating': '6.6', 'votes': '16308', 'title': 'Shanghai Noon '},
   {'seen': '0', 'rating': '6.2', 'votes': '16305', 'title': 'EuroTrip '},
   {'seen': '0', 'rating': '7.3', 'votes': '16292', 'title': 'Hurricane, The '},
   {'seen': '0', 'rating': '6.3', 'votes': '16292', 'title': 'Star Trek: Insurrection '},
   {'seen': '0', 'rating': '5.4', 'votes': '16228', 'title': 'Time Machine, The '},
   {'seen': '0', 'rating': '7.3', 'votes': '16216', 'title': 'Carrie '},
   {'seen': '0', 'rating': '7.2', 'votes': '16177', 'title': 'In the Line of Fire '},
   {'seen': '0', 'rating': '7.8', 'votes': '16170', 'title': 'Before Sunrise '},
   {'seen': '0', 'rating': '6.8', 'votes': '16158', 'title': 'Patriot Games '},
   {'seen': '0', 'rating': '8', 'votes': '16153', 'title': 'Festen '},
   {'seen': '0', 'rating': '5.7', 'votes': '16129', 'title': 'Nutty Professor, The '},
   {'seen': '0', 'rating': '7.1', 'votes': '16126', 'title': 'Runaway Jury '},
   {'seen': '0', 'rating': '7.8', 'votes': '16120', 'title': 'My Fair Lady '},
   {'seen': '0', 'rating': '8.4', 'votes': '16079', 'title': 'Double Indemnity '},
   {'seen': '0', 'rating': '6.5', 'votes': '16062', 'title': 'Birdcage, The '},
   {'seen': '0', 'rating': '5.7', 'votes': '16055', 'title': 'Blade: Trinity '},
   {'seen': '0', 'rating': '5.7', 'votes': '16041', 'title': 'Reign of Fire '},
   {'seen': '0', 'rating': '7.5', 'votes': '16019', 'title': 'Seabiscuit '},
   {'seen': '0', 'rating': '7.5', 'votes': '15997', 'title': 'Braindead '},
   {'seen': '0', 'rating': '6.6', 'votes': '15996', 'title': 'Underworld: Evolution '},
   {'seen': '0', 'rating': '7.2', 'votes': '15976', 'title': 'Dr. No '},
   {'seen': '0', 'rating': '5.3', 'votes': '15971', 'title': 'Scary Movie 3 '},
   {'seen': '0', 'rating': '5.7', 'votes': '15947', 'title': 'Saint, The '},
   {'seen': '0', 'rating': '6.5', 'votes': '15931', 'title': 'Backdraft '},
   {'seen': '0', 'rating': '7.6', 'votes': '15922', 'title': 'Super Size Me '},
   {'seen': '0', 'rating': '6.5', 'votes': '15921', 'title': 'Long Kiss Goodnight, The '},
   {'seen': '0', 'rating': '5.9', 'votes': '15905', 'title': 'Bring It On '},
   {'seen': '0', 'rating': '6.4', 'votes': '15902', 'title': 'While You Were Sleeping '},
   {'seen': '0', 'rating': '8.4', 'votes': '15900', 'title': 'Rebecca '},
   {'seen': '0', 'rating': '7.6', 'votes': '15880', 'title': 'Player, The '},
   {'seen': '0', 'rating': '5.9', 'votes': '15879', 'title': 'Brothers Grimm, The '},
   {'seen': '0', 'rating': '7.7', 'votes': '15870', 'title': 'Dirty Harry '},
   {'seen': '0', 'rating': '7.4', 'votes': '15852', 'title': 'Broken Flowers '},
   {'seen': '0', 'rating': '5.8', 'votes': '15836', 'title': '6th Day, The '},
   {'seen': '0', 'rating': '7.9', 'votes': '15834', 'title': 'French Connection, The '},
   {'seen': '0', 'rating': '6', 'votes': '15833', 'title': 'Freddy vs. Jason '},
   {'seen': '0', 'rating': '6.1', 'votes': '15833', 'title': 'Patch Adams '},
   {'seen': '0', 'rating': '6.2', 'votes': '15819', 'title': 'Running Man, The '},
   {'seen': '0', 'rating': '2.3', 'votes': '15816', 'title': 'Gigli '},
   {'seen': '0', 'rating': '6.1', 'votes': '15804', 'title': 'Paycheck '},
   {'seen': '0', 'rating': '7.5', 'votes': '15778', 'title': 'Mad Max 2 '},
   {'seen': '0', 'rating': '8.3', 'votes': '15770', 'title': 'Mr. Smith Goes to Washington '},
   {'seen': '0', 'rating': '7', 'votes': '15732', 'title': 'Born on the Fourth of July '},
   {'seen': '0', 'rating': '7.6', 'votes': '15730', 'title': 'Dangerous Liaisons '},
   {'seen': '0', 'rating': '7.3', 'votes': '15711', 'title': 'Piano, The '},
   {'seen': '0', 'rating': '7.3', 'votes': '15710', 'title': 'Planes, Trains & Automobiles '},
   {'seen': '0', 'rating': '7.8', 'votes': '15701', 'title': 'Right Stuff, The '},
   {'seen': '0', 'rating': '6.8', 'votes': '15695', 'title': 'Mad Max '},
   {'seen': '0', 'rating': '5.8', 'votes': '15693', 'title': 'Along Came Polly '},
   {'seen': '0', 'rating': '7.2', 'votes': '15680', 'title': 'People vs. Larry Flynt, The '},
   {'seen': '0', 'rating': '6.7', 'votes': '15679', 'title': 'Hostage '},
   {'seen': '0', 'rating': '8.4', 'votes': '15677', 'title': 'Touch of Evil '},
   {'seen': '0', 'rating': '5.9', 'votes': '15669', 'title': 'Texas Chainsaw Massacre, The '},
   {'seen': '0', 'rating': '6.5', 'votes': '15629', 'title': 'Star Trek: Nemesis '},
   {'seen': '0', 'rating': '6.3', 'votes': '15620', 'title': 'Star Trek: Generations '},
   {'seen': '0', 'rating': '6.3', 'votes': '15601', 'title': 'What Dreams May Come '},
   {'seen': '0', 'rating': '7.7', 'votes': '15569', 'title': 'Name der Rose, Der '},
   {'seen': '0', 'rating': '5.7', 'votes': '15568', 'title': 'Snake Eyes '},
   {'seen': '0', 'rating': '7.8', 'votes': '15552', 'title': 'Glengarry Glen Ross '},
   {'seen': '0', 'rating': '7.2', 'votes': '15544', 'title': 'Elephant '},
   {'seen': '0', 'rating': '5', 'votes': '15535', 'title': '2 Fast 2 Furious '},
   {'seen': '0', 'rating': '8.3', 'votes': '15467', 'title': 'Apartment, The '},
   {'seen': '0', 'rating': '6.5', 'votes': '15411', 'title': 'Family Man, The '},
   {'seen': '0', 'rating': '7', 'votes': '15382', 'title': 'Memoirs of a Geisha '},
   {'seen': '0', 'rating': '5.8', 'votes': '15347', 'title': 'Gothika '},
   {'seen': '0', 'rating': '5.3', 'votes': '15345', 'title': 'Bodyguard, The '},
   {'seen': '0', 'rating': '5.7', 'votes': '15341', 'title': "America's Sweethearts "},
   {'seen': '0', 'rating': '7.4', 'votes': '15340', 'title': 'Poltergeist '},
   {'seen': '0', 'rating': '5.3', 'votes': '15333', 'title': 'Not Another Teen Movie '},
   {'seen': '0', 'rating': '5.8', 'votes': '15331', 'title': 'Commando '},
   {'seen': '0', 'rating': '7.4', 'votes': '15326', 'title': 'Awakenings '},
   {'seen': '0', 'rating': '7.9', 'votes': '15326', 'title': 'United 93 '},
   {'seen': '0', 'rating': '7.7', 'votes': '15312', 'title': 'Happiness '},
   {'seen': '0', 'rating': '6.3', 'votes': '15283', 'title': 'Space Cowboys '},
   {'seen': '0', 'rating': '3.3', 'votes': '15252', 'title': 'Catwoman '},
   {'seen': '0', 'rating': '6.4', 'votes': '15247', 'title': 'Crocodile Dundee '},
   {'seen': '0', 'rating': '7.4', 'votes': '15237', 'title': 'Fisher King, The '},
   {'seen': '0', 'rating': '6.7', 'votes': '15207', 'title': 'Lost Boys, The '},
   {'seen': '0', 'rating': '5.3', 'votes': '15170', 'title': 'Doom '},
   {'seen': '0', 'rating': '5.9', 'votes': '15152', 'title': 'Man in the Iron Mask, The '},
   {'seen': '0', 'rating': '7.8', 'votes': '15143', 'title': 'Good Bye Lenin! '},
   {'seen': '0', 'rating': '6.2', 'votes': '15126', 'title': 'Phenomenon '},
   {'seen': '0', 'rating': '5.8', 'votes': '15119', 'title': 'Bedazzled '},
   {'seen': '0', 'rating': '6.5', 'votes': '15066', 'title': 'Point Break '},
   {'seen': '0', 'rating': '7.9', 'votes': '15060', 'title': 'Delicatessen '},
   {'seen': '0', 'rating': '8.3', 'votes': '15059', 'title': 'Great Dictator, The '},
   {'seen': '0', 'rating': '8', 'votes': '15052', 'title': 'Arsenic and Old Lace '},
   {'seen': '0', 'rating': '7.4', 'votes': '15031', 'title': 'Best in Show '},
   {'seen': '0', 'rating': '5.5', 'votes': '15028', 'title': 'Net, The '},
   {'seen': '0', 'rating': '7.4', 'votes': '15019', 'title': 'Much Ado About Nothing '},
   {'seen': '0', 'rating': '6.4', 'votes': '15018', 'title': 'Addams Family, The '},
   {'seen': '0', 'rating': '6.5', 'votes': '15010', 'title': 'Serendipity '},
   {'seen': '0', 'rating': '5.3', 'votes': '15002', 'title': 'Jeepers Creepers '},
   {'seen': '0', 'rating': '7.2', 'votes': '15000', 'title': 'Wall Street '},
   {'seen': '0', 'rating': '7.2', 'votes': '14999', 'title': 'Texas Chain Saw Massacre, The '},
   {'seen': '0', 'rating': '6.8', 'votes': '14997', 'title': 'Sliding Doors '},
   {'seen': '0', 'rating': '5.8', 'votes': '14928', 'title': 'Robin Hood: Men in Tights '},
   {'seen': '0', 'rating': '6.9', 'votes': '14914', 'title': 'Big Trouble in Little China '},
   {'seen': '0', 'rating': '8.3', 'votes': '14896', 'title': 'Strangers on a Train '},
   {'seen': '0', 'rating': '7.2', 'votes': '14891', 'title': 'I Am Sam '},
   {'seen': '0', 'rating': '7.1', 'votes': '14878', 'title': 'Mulan '},
   {'seen': '0', 'rating': '6', 'votes': '14873', 'title': 'Behind Enemy Lines '},
   {'seen': '0', 'rating': '7', 'votes': '14832', 'title': 'Sneakers '},
   {'seen': '0', 'rating': '7.6', 'votes': '14828', 'title': 'Heavenly Creatures '},
   {'seen': '0', 'rating': '7', 'votes': '14815', 'title': 'Stir of Echoes '},
   {'seen': '0', 'rating': '6.5', 'votes': '14765', 'title': 'That Thing You Do! '},
   {'seen': '0', 'rating': '7.5', 'votes': '14754', 'title': 'Shine '},
   {'seen': '0', 'rating': '7.3', 'votes': '14751', 'title': 'Trading Places '},
   {'seen': '0', 'rating': '6.9', 'votes': '14750', 'title': 'Strange Days '},
   {'seen': '0', 'rating': '6.1', 'votes': '14745', 'title': 'Four Rooms '},
   {'seen': '0', 'rating': '3.8', 'votes': '14738', 'title': 'Showgirls '},
   {'seen': '0', 'rating': '7.9', 'votes': '14735', 'title': 'Rebel Without a Cause '},
   {'seen': '0', 'rating': '6.6', 'votes': '14703', 'title': 'Karate Kid, The '},
   {'seen': '0', 'rating': '8.4', 'votes': '14698', 'title': 'Modern Times '},
   {'seen': '0', 'rating': '5.2', 'votes': '14697', 'title': 'Dreamcatcher '},
   {'seen': '0', 'rating': '6.9', 'votes': '14680', 'title': 'Willow '},
   {'seen': '0', 'rating': '6', 'votes': '14666', 'title': 'Shark Tale '},
   {'seen': '0', 'rating': '7.6', 'votes': '14626', 'title': 'Dead Man '},
   {'seen': '0', 'rating': '7.4', 'votes': '14625', 'title': 'Bound '},
   {'seen': '0', 'rating': '6.4', 'votes': '14624', 'title': 'Mothman Prophecies, The '},
   {'seen': '0', 'rating': '6.5', 'votes': '14616', 'title': 'Superman II '},
   {'seen': '0', 'rating': '8.3', 'votes': '14606', 'title': 'Notorious '},
   {'seen': '0', 'rating': '6.8', 'votes': '14605', 'title': 'American President, The '},
   {'seen': '0', 'rating': '7.2', 'votes': '14577', 'title': 'Star Trek IV: The Voyage Home '},
   {'seen': '0', 'rating': '8', 'votes': '14535', 'title': 'Wild Bunch, The '},
   {'seen': '0', 'rating': '7.5', 'votes': '14532', 'title': 'Empire of the Sun '},
   {'seen': '0', 'rating': '7.3', 'votes': '14520', 'title': 'Excalibur '},
   {'seen': '0', 'rating': '6.2', 'votes': '14444', 'title': 'Hot Shots! '},
   {'seen': '0', 'rating': '7.2', 'votes': '14433', 'title': 'Lilo & Stitch '},
   {'seen': '0', 'rating': '7.3', 'votes': '14423', 'title': 'Frailty '},
   {'seen': '0', 'rating': '7.2', 'votes': '14372', 'title': 'My Cousin Vinny '},
   {'seen': '0', 'rating': '8.4', 'votes': '14371', 'title': 'Sjunde inseglet, Det '},
   {'seen': '0', 'rating': '7.2', 'votes': '14353', 'title': 'Easy Rider '},
   {'seen': '0', 'rating': '4', 'votes': '14341', 'title': 'Anaconda '},
   {'seen': '0', 'rating': '8.5', 'votes': '14335', 'title': 'Treasure of the Sierra Madre, The '},
   {'seen': '0', 'rating': '7.3', 'votes': '14326', 'title': 'Heathers '},
   {'seen': '0', 'rating': '8.2', 'votes': '14324', 'title': 'Per qualche dollaro in pi'},
   {'seen': '0', 'rating': '7.6', 'votes': '14306', 'title': 'Color Purple, The '},
   {'seen': '0', 'rating': '5.5', 'votes': '14306', 'title': 'Six Days Seven Nights '},
   {'seen': '0', 'rating': '6.5', 'votes': '14266', 'title': 'Kingpin '},
   {'seen': '0', 'rating': '8.1', 'votes': '14265', 'title': 'Conversation, The '},
   {'seen': '0', 'rating': '5.6', 'votes': '14264', 'title': 'Never Been Kissed '},
   {'seen': '0', 'rating': '7.4', 'votes': '14262', 'title': 'Quiz Show '},
   {'seen': '0', 'rating': '7.2', 'votes': '14253', 'title': 'Secretary '},
   {'seen': '0', 'rating': '7', 'votes': '14216', 'title': 'Amistad '},
   {'seen': '0', 'rating': '7', 'votes': '14211', 'title': 'WarGames '},
   {'seen': '0', 'rating': '8', 'votes': '14206', 'title': 'Doctor Zhivago '},
   {'seen': '0', 'rating': '8.1', 'votes': '14188', 'title': 'Clerks II '},
   {'seen': '0', 'rating': '7.9', 'votes': '14177', 'title': 'Being There '},
   {'seen': '0', 'rating': '7.8', 'votes': '14173', 'title': 'Cit'},
   {'seen': '0', 'rating': '6.1', 'votes': '14171', 'title': 'How to Lose a Guy in 10 Days '},
   {'seen': '0', 'rating': '8.6', 'votes': '14165', 'title': 'Departed, The '},
   {'seen': '0', 'rating': '7.2', 'votes': '14138', 'title': 'Danny the Dog '},
   {'seen': '0', 'rating': '5.8', 'votes': '14137', 'title': 'Beverly Hills Cop II '},
   {'seen': '0', 'rating': '6.6', 'votes': '14123', 'title': 'Keeping the Faith '},
   {'seen': '0', 'rating': '6', 'votes': '14104', 'title': "General's Daughter, The "},
   {'seen': '0', 'rating': '4.8', 'votes': '14100', 'title': 'Little Nicky '},
   {'seen': '0', 'rating': '5.4', 'votes': '14094', 'title': "Look Who's Talking "},
   {'seen': '0', 'rating': '6.1', 'votes': '14080', 'title': '15 Minutes '},
   {'seen': '0', 'rating': '7.1', 'votes': '14080', 'title': 'Fast Times at Ridgemont High '},
   {'seen': '0', 'rating': '5.7', 'votes': '14077', 'title': 'Sweet Home Alabama '},
   {'seen': '0', 'rating': '6.3', 'votes': '14071', 'title': 'Final Destination 2 '},
   {'seen': '0', 'rating': '5.7', 'votes': '14055', 'title': 'Rocky III '},
   {'seen': '0', 'rating': '5.8', 'votes': '14051', 'title': 'Forgotten, The '},
   {'seen': '0', 'rating': '5.2', 'votes': '14049', 'title': 'Scorpion King, The '},
   {'seen': '0', 'rating': '8.1', 'votes': '14043', 'title': 'Philadelphia Story, The '},
   {'seen': '0', 'rating': '7.1', 'votes': '14029', 'title': 'Fly, The '},
   {'seen': '0', 'rating': '7.7', 'votes': '13997', 'title': 'Boyz n the Hood '},
   {'seen': '0', 'rating': '6.9', 'votes': '13976', 'title': 'Frighteners, The '},
   {'seen': '0', 'rating': '7.1', 'votes': '13968', 'title': 'Thirteen '},
   {'seen': '0', 'rating': '8', 'votes': '13953', 'title': 'Searchers, The '},
   {'seen': '0', 'rating': '7.9', 'votes': '13944', 'title': 'Per un pugno di dollari '},
   {'seen': '0', 'rating': '5.6', 'votes': '13942', 'title': 'Predator 2 '},
   {'seen': '0', 'rating': '6.7', 'votes': '13935', 'title': 'Doors, The '},
   {'seen': '0', 'rating': '7.4', 'votes': '13924', 'title': 'From Russia with Love '},
   {'seen': '0', 'rating': '6.1', 'votes': '13914', 'title': 'Dragonheart '},
   {'seen': '0', 'rating': '7.5', 'votes': '13902', 'title': 'Say Anything... '},
   {'seen': '0', 'rating': '7.5', 'votes': '13882', 'title': 'Nikita '},
   {'seen': '0', 'rating': '3.3', 'votes': '13877', 'title': 'Avengers, The '},
   {'seen': '0', 'rating': '8.1', 'votes': '13857', 'title': 'Day the Earth Stood Still, The '},
   {'seen': '0', 'rating': '5.6', 'votes': '13838', 'title': 'Hackers '},
   {'seen': '0', 'rating': '5.5', 'votes': '13824', 'title': 'Deuce Bigalow: Male Gigolo '},
   {'seen': '0', 'rating': '7.8', 'votes': '13824', 'title': 'Whale Rider '},
   {'seen': '0', 'rating': '8', 'votes': '13802', 'title': 'Streetcar Named Desire, A '},
   {'seen': '0', 'rating': '8', 'votes': '13794', 'title': 'Trois couleurs: Rouge '},
   {'seen': '0', 'rating': '7.3', 'votes': '13772', 'title': 'Thirteen Days '},
   {'seen': '0', 'rating': '6.4', 'votes': '13736', 'title': 'Last Boy Scout, The '},
   {'seen': '0', 'rating': '7.5', 'votes': '13731', 'title': 'Barton Fink '},
   {'seen': '0', 'rating': '6', 'votes': '13702', 'title': 'Star Trek: The Motion Picture '},
   {'seen': '0', 'rating': '8.2', 'votes': '13698', 'title': 'Little Miss Sunshine '},
   {'seen': '0', 'rating': '7.8', 'votes': '13687', 'title': 'Magnificent Seven, The '},
   {'seen': '0', 'rating': '8.3', 'votes': '13682', 'title': 'Big Sleep, The '},
   {'seen': '0', 'rating': '6.6', 'votes': '13677', 'title': 'U Turn '},
   {'seen': '0', 'rating': '7.1', 'votes': '13670', 'title': 'Christmas Vacation '},
   {'seen': '0', 'rating': '7.3', 'votes': '13640', 'title': 'Fried Green Tomatoes '},
   {'seen': '0', 'rating': '5.2', 'votes': '13626', 'title': 'Lara Croft Tomb Raider: The Cradle of Life '},
   {'seen': '0', 'rating': '6.9', 'votes': '13602', 'title': 'Tarzan '},
   {'seen': '0', 'rating': '5.6', 'votes': '13595', 'title': 'Be Cool '},
   {'seen': '0', 'rating': '6.9', 'votes': '13579', 'title': 'Jacket, The '},
   {'seen': '0', 'rating': '6.8', 'votes': '13560', 'title': 'Escape from New York '},
   {'seen': '0', 'rating': '6.2', 'votes': '13530', 'title': 'Miami Vice '},
   {'seen': '0', 'rating': '4.5', 'votes': '13438', 'title': 'Judge Dredd '},
   {'seen': '0', 'rating': '6.3', 'votes': '13429', 'title': 'Rocky II '},
   {'seen': '0', 'rating': '6.6', 'votes': '13428', 'title': 'Men of Honor '},
   {'seen': '0', 'rating': '7.8', 'votes': '13410', 'title': 'K'},
   {'seen': '0', 'rating': '5.5', 'votes': '13407', 'title': ''},
   {'seen': '0', 'rating': '5.2', 'votes': '13404', 'title': 'Rambo: First Blood Part II '},
   {'seen': '0', 'rating': '6.3', 'votes': '13396', 'title': 'Tears of the Sun '},
   {'seen': '0', 'rating': '7.9', 'votes': '13385', 'title': 'Network '},
   {'seen': '0', 'rating': '6.9', 'votes': '13378', 'title': 'Ever After '},
   {'seen': '0', 'rating': '7.8', 'votes': '13377', 'title': 'In the Name of the Father '},
   {'seen': '0', 'rating': '7.7', 'votes': '13373', 'title': 'House of Sand and Fog '},
   {'seen': '0', 'rating': '7.9', 'votes': '13350', 'title': 'Un long dimanche de fian'},
   {'seen': '0', 'rating': '6.1', 'votes': '13332', 'title': 'U.S. Marshals '},
   {'seen': '0', 'rating': '7', 'votes': '13299', 'title': 'Tremors '},
   {'seen': '0', 'rating': '8.1', 'votes': '13298', 'title': 'Duck Soup '},
   {'seen': '0', 'rating': '7.7', 'votes': '13296', 'title': 'Cars '},
   {'seen': '0', 'rating': '5.6', 'votes': '13296', 'title': 'Death Becomes Her '},
   {'seen': '0', 'rating': '6.8', 'votes': '13281', 'title': 'Four Brothers '},
   {'seen': '0', 'rating': '6.2', 'votes': '13280', 'title': 'Messenger: The Story of Joan of Arc, The '},
   {'seen': '0', 'rating': '5.7', 'votes': '13273', 'title': 'Romeo Must Die '},
   {'seen': '0', 'rating': '8', 'votes': '13236', 'title': 'Roman Holiday '},
   {'seen': '0', 'rating': '6.3', 'votes': '13222', 'title': 'Pelican Brief, The '},
   {'seen': '0', 'rating': '6.4', 'votes': '13199', 'title': 'Hills Have Eyes, The '},
   {'seen': '0', 'rating': '7', 'votes': '13194', 'title': 'Wild at Heart '},
   {'seen': '0', 'rating': '7.6', 'votes': '13193', 'title': 'Breaking the Waves '},
   {'seen': '0', 'rating': '7.5', 'votes': '13181', 'title': 'Bronx Tale, A '},
   {'seen': '0', 'rating': '5.1', 'votes': '13181', 'title': 'Ring Two, The '},
   {'seen': '0', 'rating': '6.3', 'votes': '13171', 'title': 'Ali '},
   {'seen': '0', 'rating': '6.9', 'votes': '13164', 'title': 'Click '},
   {'seen': '0', 'rating': '7.9', 'votes': '13142', 'title': 'Papillon '},
   {'seen': '0', 'rating': '7.1', 'votes': '13139', 'title': 'Star Trek VI: The Undiscovered Country '},
   {'seen': '0', 'rating': '5.4', 'votes': '13129', 'title': 'Vertical Limit '},
   {'seen': '0', 'rating': '6', 'votes': '13101', 'title': 'Sahara '},
   {'seen': '0', 'rating': '5.9', 'votes': '13092', 'title': 'Sister Act '},
   {'seen': '0', 'rating': '7.5', 'votes': '13089', 'title': 'Pink Floyd The Wall '},
   {'seen': '0', 'rating': '5.6', 'votes': '13089', 'title': "Wayne's World 2 "},
   {'seen': '0', 'rating': '8.2', 'votes': '13087', 'title': 'Yojimbo '},
   {'seen': '0', 'rating': '6.8', 'votes': '13073', 'title': 'Exorcism of Emily Rose, The '},
   {'seen': '0', 'rating': '5.7', 'votes': '13037', 'title': 'Dick Tracy '},
   {'seen': '0', 'rating': '6.4', 'votes': '13033', 'title': 'Naked Gun 2'},
   {'seen': '0', 'rating': '7.5', 'votes': '13025', 'title': 'Bambi '},
   {'seen': '0', 'rating': '4.6', 'votes': '13015', 'title': 'Scooby-Doo '},
   {'seen': '0', 'rating': '6.1', 'votes': '13012', 'title': "Don't Say a Word "},
   {'seen': '0', 'rating': '6.3', 'votes': '12998', 'title': 'Longest Yard, The '},
   {'seen': '0', 'rating': '6.4', 'votes': '12964', 'title': 'John Q '},
   {'seen': '0', 'rating': '6.5', 'votes': '12962', 'title': 'Cellular '},
   {'seen': '0', 'rating': '6.8', 'votes': '12949', 'title': 'Dave '},
   {'seen': '0', 'rating': '6.1', 'votes': '12922', 'title': 'Edtv '},
   {'seen': '0', 'rating': '3.6', 'votes': '12916', 'title': 'Freddy Got Fingered '},
   {'seen': '0', 'rating': '5.5', 'votes': '12909', 'title': 'Hide and Seek '}
];

// missing a guid property - map one in
(function() {
  var guid = 1;
  TableView.Movie.FIXTURES.forEach(function(rec) {
    rec.guid = guid++;
  }, this);
})();
